/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceSection: typeof import('./src/components/shell/settings/AppearanceSection.vue')['default']
    DataSection: typeof import('./src/components/shell/settings/DataSection.vue')['default']
    DevicesSection: typeof import('./src/components/shell/settings/DevicesSection.vue')['default']
    GeneralSection: typeof import('./src/components/shell/settings/GeneralSection.vue')['default']
    InputsInspector: typeof import('./src/components/shell/InputsInspector.vue')['default']
    LedMap: typeof import('./src/components/panels/LedMap.vue')['default']
    LedStrip: typeof import('./src/components/panels/LedStrip.vue')['default']
    LiveIndicator: typeof import('./src/components/shell/LiveIndicator.vue')['default']
    LogPanel: typeof import('./src/components/panels/LogPanel.vue')['default']
    MatchText: typeof import('./src/components/reference/MatchText.vue')['default']
    OutputButton: typeof import('./src/components/shell/OutputButton.vue')['default']
    OutputInspector: typeof import('./src/components/shell/OutputInspector.vue')['default']
    OutputSection: typeof import('./src/components/shell/settings/OutputSection.vue')['default']
    PerformancePanel: typeof import('./src/components/shell/PerformancePanel.vue')['default']
    PreviewPanel: typeof import('./src/components/panels/PreviewPanel.vue')['default']
    ReferenceEntry: typeof import('./src/components/reference/ReferenceEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./src/components/shell/SettingsView.vue')['default']
    ShareAudioPrompt: typeof import('./src/components/shell/ShareAudioPrompt.vue')['default']
    ShortcutsSection: typeof import('./src/components/shell/settings/ShortcutsSection.vue')['default']
    TransportGroup: typeof import('./src/components/shell/TransportGroup.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContextMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
