/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LogPanel: typeof import('./src/components/panels/LogPanel.vue')['default']
    PerformancePanel: typeof import('./src/components/shell/PerformancePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContextMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.1_91f066730fccded5785077c799dc74ba/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
