import type { NodeItem } from '@/lib/graph/define/shape'
import { AUDIO_NODES } from './audio'
import { COLOR_NODES } from './color'
import { CONTROL_NODES } from './control'
import { CONVERTER_NODES } from './converter'
import { INPUT_NODES } from './input'
import { OUTPUT_NODES } from './output'
import { SIGNAL_NODES } from './signal'
import { SPATIAL_NODES } from './spatial'
import { TEXTURE_NODES } from './texture'

export const NODE_KINDS: NodeItem[] = [
  ...AUDIO_NODES,
  ...COLOR_NODES,
  ...CONTROL_NODES,
  ...CONVERTER_NODES,
  ...INPUT_NODES,
  ...OUTPUT_NODES,
  ...SIGNAL_NODES,
  ...SPATIAL_NODES,
  ...TEXTURE_NODES,
]

// the menu still names node consts until it names kinds by id
export { audioNode, audioSourceNode, bandSplitNode, fftNode } from './audio/audio'
export { audioSignalNode } from './audio/audio-signal'
export { bandsNode } from './audio/bands'
export { chromaNode, spectrumNode, waveformNode } from './audio/samplers'
export { brightnessContrastNode, gammaNode, invertNode } from './color/adjust'
export { colorNode } from './color/color'
export { colorMixNode } from './color/color-mix'
export { colorRampNode } from './color/color-ramp'
export { brightnessCeilingNode, layerMixNode, maskNode } from './color/composite'
export { hsvToRgbNode, hueSaturationNode, rgbToHsvNode } from './color/hsv'
export { paletteNode } from './color/palette'
export { combineColorNode, separateColorNode } from './color/separate-combine'
export { knobNode } from './control/knob'
export { midiInNode, oscInNode } from './control/midi-osc'
export { sceneSwitchNode } from './control/scene-switch'
export { timeNode } from './control/time'
export { clampNode } from './converter/clamp'
export { mathNode } from './converter/math'
export { mixNode } from './converter/mix'
export { vectorMathNode } from './converter/vector-math'
export { combineXyzNode, separateXyzNode } from './converter/xyz'
export { uvNode } from './input/uv'
export { valueNode } from './input/value'
export { vector2Node } from './input/vector2'
export { outputNode } from './output/output'
export { clockDividerNode } from './signal/clock-divider'
export { counterNode, toggleNode } from './signal/counter'
export { curveNode } from './signal/curve'
export { envelopeNode } from './signal/envelope'
export { envelopeFollowerNode } from './signal/envelope-follower'
export { integratorNode } from './signal/integrator'
export { mapRangeNode } from './signal/map-range'
export { peakHoldNode } from './signal/peak-hold'
export { randomNode } from './signal/random'
export { sampleHoldNode } from './signal/sample-hold'
export { schmittTriggerNode } from './signal/schmitt-trigger'
export { slewLimiterNode } from './signal/slew-limiter'
export { stepSequencerNode } from './signal/step-sequencer'
export { viewerNode } from './signal/viewer'
export { waveNode } from './signal/wave'
export { previousFrameNode, stripBlurNode, trailsNode } from './spatial/feedback'
export { fromCenterNode } from './spatial/from-center'
export { ledLayoutNode } from './spatial/led-layout'
export { mappingNode } from './spatial/mapping'
export { rangeSelectNode } from './spatial/range-select'
export { mirrorNode, polarNode, rotateNode, segmentSplitNode, tileNode } from './spatial/transforms'
export { brickTextureNode } from './texture/brick-texture'
export { checkerTextureNode } from './texture/checker-texture'
export { gradientTextureNode } from './texture/gradient-texture'
export { imageTextureNode } from './texture/image-texture'
export { magicTextureNode } from './texture/magic-texture'
export { noiseTextureNode } from './texture/noise-texture'
export { voronoiNode, whiteNoiseNode } from './texture/noise-textures'
export { waveTextureNode } from './texture/wave-texture'
