// One C++ translation unit holding every node kind alone with its defaults, as the GLSL backend emits it in standalone
// mode. CI compiles it against cpp/wledtoy.h, so a pixel body that leaks a GLSL-only construct fails the build.
import type { NodeItem } from '@/lib/graph/define/shape'
import { allItems } from '@/lib/graph/registry'
import { alone } from '@/lib/graph/testing'
import { buildProgram } from './compile'
import { glsl } from './glsl'

export interface CppUnit {
  code: string
  /** Kinds whose pixel body declared `ctx.require('glsl')`, so the unit leaves them out. */
  excluded: string[]
}

export function cppUnit(): CppUnit {
  const kinds = allItems().map((item) => ({ id: item.id, ...standaloneCode(item) }))
  // each kind gets a namespace of its own: two kinds that include the same chunk would otherwise define it twice
  const namespaces = kinds.filter((kind) => !kind.glslOnly).map((kind) => `namespace kind_${kind.id} {\n${cppDeclarations(kind.code)}}\n`)
  const code = ['// Generated by scripts/gen-cpp-unit.ts; do not edit.', '#include "../wledtoy.h"', '', 'namespace wledtoy {', '', ...namespaces, '}', '']
  return { code: code.join('\n'), excluded: kinds.filter((kind) => kind.glslOnly).map((kind) => kind.id) }
}

function standaloneCode(item: NodeItem): { code: string; glslOnly: boolean } {
  const program = buildProgram(alone(item), { standalone: true, controls: () => 0.5 })
  const { code, error } = glsl(program)
  if (error) throw new Error(`${item.id}: ${error}`)
  return { code, glslOnly: program.nodes.n?.requires?.includes('glsl') ?? false }
}

// C++ spells a GLSL `out` parameter as a reference. A node variable (`n_` prefix) holds an output whether or not
// anything reads it, so only a stray local of a body or chunk is reported as unused.
const cppDeclarations = (code: string) =>
  code.replace(/\bout\s+(float|int|vec[234])\s/g, '$1& ').replace(/\b(float|int|vec[234]) (n_\w+)(?=\s*[=;])/g, '[[maybe_unused]] $1 $2')
