// The numeric parity unit: every Math and Vector Math operation on a fixed set of stored inputs, each compiled through
// cpp(program), beside what the node's frame body gives for the same inputs. The binary judges itself (cpp/parity.h).
import type { FrameValue } from '@/lib/graph/define/context'
import type { SocketValue } from '@/lib/graph/model/doc'
import { MATH_OPS } from '@/lib/graph/nodes/converter/math'
import { VECTOR_OPS } from '@/lib/graph/nodes/converter/vector-math'
import { itemFor } from '@/lib/graph/registry'
import { graph, node } from '@/lib/graph/testing'
import { buildProgram } from './compile'
import { cppDefinitions } from './cpp'

// Dyadic fractions, exact in a float and in the four decimals a GLSL literal keeps, so a result differs only by the
// arithmetic. They cover negatives, zero, a zero divisor or range, and the equal operands that step() edges turn on.
const MATH_INPUTS: [number, number, number][] = [
  [-2.5, 2, 0.5], [-0.75, -1.5, 0.25], [0, 0.5, 0], [0.375, 0, 1.25], [0.75, 0.25, 0.5],
  [1.25, 3, -0.75], [3, -2, 2.5], [-1.25, 0.5, 0.5], [0.25, 0.375, 1], [0.5, 0.5, 0.125], [2, 1, 0.25],
]

const VECTOR_INPUTS: { a: number[]; b: number[]; c: number[]; scale: number }[] = [
  { a: [-2.5, 0.375, 1.25], b: [0.5, -1.5, 2], c: [1, 0.25, -0.75], scale: 2 },
  { a: [0, 0, 0], b: [0.25, 0, -0.5], c: [0.5, 0.5, 0.5], scale: -0.75 },
  { a: [3, -0.75, 0.5], b: [-1.25, 2, 0.25], c: [-1.25, 3, 0.25], scale: 0 },
  { a: [0.75, -2, -0.375], b: [1, 1, 1], c: [0, -0.5, 1.5], scale: 0.5 },
  { a: [1.25, 0.5, -1], b: [-0.75, 0.25, 0.5], c: [2, 1, 0], scale: -1.5 },
  { a: [1.25, -0.5, 0.75], b: [0, 0, 0], c: [0.25, -1, 2], scale: 3 },
]

// Reflect normalizes `b`, and GLSL's normalize of the zero vector is undefined where the frame body's is 0
const skipped = (op: string, values: Record<string, SocketValue>) =>
  op === 'reflect' && (values.b as number[]).every((component) => component === 0)

interface ParityOp {
  name: string
  kind: string
  cases: Record<string, SocketValue>[]
}

export interface ParityUnit {
  code: string
  /** `math.add`, `vectorMath.cross`, ...: one per operation in the tables, in table order. */
  ops: string[]
}

export function cppParity(): ParityUnit {
  const ops = parityOps()
  const code = ['// Generated by scripts/gen-cpp-unit.ts; do not edit.', '#include "parity.h"', '', 'namespace wledtoy {', '', ...ops.flatMap(opDefinitions), '}', '', ...ops.flatMap(opTable), ...main(ops)]
  return { code: code.join('\n'), ops: ops.map((op) => op.name) }
}

function parityOps(): ParityOp[] {
  const math = Object.keys(MATH_OPS).map((op) => ({ name: `math.${op}`, kind: 'math', cases: MATH_INPUTS.map(([a, b, c]) => ({ op, a, b, c })) }))
  const vector = Object.keys(VECTOR_OPS).map((op) => ({ name: `vectorMath.${op}`, kind: 'vectorMath', cases: VECTOR_INPUTS.map((inputs) => ({ op, ...inputs })).filter((values) => !skipped(op, values)) }))
  return [...math, ...vector].map((op) => ({ ...op, cases: op.cases.map((values) => socketValues(op.kind, values)) }))
}

/** Only the values the operation has sockets for: a unary Math takes no `b`. */
function socketValues(kind: string, values: Record<string, SocketValue>): Record<string, SocketValue> {
  const shape = itemFor(kind)!.shape(values)
  return Object.fromEntries(shape.inputs.filter((socket) => socket.name in values).map((socket) => [socket.name, values[socket.name]]))
}

const tableName = (op: ParityOp) => op.name.replace('.', '_')
const caseNamespace = (op: ParityOp, i: number) => `${tableName(op)}_${i}`

function opDefinitions(op: ParityOp): string[] {
  return op.cases.map((values, i) => {
    const doc = graph([node('n', op.kind, values), node('o', 'output')], [[`n.${itemFor(op.kind)!.shape(values).outputs[0].name}`, 'o.color']])
    return `namespace ${caseNamespace(op, i)} {\n${cppDefinitions(buildProgram(doc, {}), { leds: 1 })}}\n`
  })
}

function opTable(op: ParityOp): string[] {
  const rows = op.cases.map((values, i) => {
    const want = frameResult(op.kind, values)
    const inputs = JSON.stringify(Object.fromEntries(Object.entries(values).filter(([name]) => name !== 'op')))
    return `  {${JSON.stringify(inputs)}, wledtoy::${caseNamespace(op, i)}::mainImage, ${want.length}, {${want.map(cppDouble).join(', ')}}},`
  })
  return [`const ParityCase ${tableName(op)}[] = {`, ...rows, '};', '']
}

/** What the node's frame body puts out for the same stored values, as the JS backend would run it. */
function frameResult(kind: string, values: Record<string, SocketValue>): number[] {
  const shape = itemFor(kind)!.shape(values)
  const input = Object.fromEntries(shape.inputs.map((socket) => [socket.name, values[socket.name] ?? socket.default]))
  const result: FrameValue = shape.frame!(input, { time: 0, dt: 0, frameIndex: 0, audio: undefined, midi: undefined, osc: undefined, state: undefined, resolved: {} })[shape.outputs[0].name]
  return Array.isArray(result) ? result : [result]
}

function cppDouble(v: number): string {
  if (!Number.isFinite(v)) throw new Error(`A parity input gives ${v} in JavaScript; pick inputs with a finite result`)
  return String(v)
}

function main(ops: ParityOp[]): string[] {
  const rows = ops.map((op) => `  {"${op.name}", ${tableName(op)}, ${op.cases.length}},`)
  return ['const ParityOp ops[] = {', ...rows, '};', '', `int main() { return runParity(ops, ${ops.length}); }`, '']
}
