// The per-pixel side: turns nodes that run in the shader into GLSL lines, and assembles the finished shader.
import type { GlslType } from '@/lib/shader/glsl'
import type { GlslChunk, NodeContext } from '@/lib/graph/define/context'
import { fallsBackToImplicit, isLinkable, isStreamSocket, type InputSocket, type LinkedInputSocket } from '@/lib/graph/define/shape'
import { isGlslType } from '@/lib/graph/define/types'
import { castTo, type Value } from '@/lib/graph/define/value'
import type { GraphNodeData } from '@/lib/graph/model/doc'
import { GraphError, isGenericSocket, type Compilation } from './compilation'
import { controlOutput } from './control-plan'
import { settledInputs } from './streams'

function context(c: Compilation, nodeId: string, gen: GlslType): NodeContext {
  const base = `n_${nodeId.replace(/\W/g, '_')}`
  const variable = (suffix?: string) => (suffix ? `${base}_${suffix}` : base)
  const emit = (text: string) => c.emit(nodeId, text)
  return {
    nodeId, gen, variable, emit,
    declare: (type, expr, suffix) => {
      emit(`${type} ${variable(suffix)} = ${expr};`)
      return { expr: variable(suffix), type }
    },
    call: (fn, args, outs) => {
      const results = Object.entries(outs).map(([name, type]) => [name, { expr: variable(name), type }] as const)
      emit(`${results.map(([, out]) => `${out.type} ${out.expr};`).join(' ')} ${fn}(${[...args, ...results.map(([, out]) => out.expr)].join(', ')});`)
      return Object.fromEntries(results) as never
    },
    include: (chunk) => c.chunks.add(chunk),
    issue: (message) => c.issues.push({ nodeId, message }),
    output: (settings) => (c.output ??= settings),
  }
}

/** The GLSL value on a linked input: from the link, else the socket's implicit expression, else its stored literal. */
function linkedValue(c: Compilation, nodeId: string, data: GraphNodeData, socket: LinkedInputSocket): Value {
  const source = c.linkSource(nodeId, socket)
  const from = source && c.lookup(source.id).shape.outputs.find((out) => out.name === source.output)
  if (from && !isGlslType(from.type)) throw new GraphError(`${socket.label} needs a number or a color, not ${from.type.label}`, nodeId)
  const linked = source && (c.placedAt(source.id) === 'frame' ? controlOutput(c, source.id, source.output) : evaluate(c, source.id)[source.output])
  if (linked) return linked
  if (fallsBackToImplicit(data.values, socket)) {
    return { expr: socket.default.expr, type: socket.type.glsl === 'genType' ? 'float' : socket.type.glsl }
  }
  return socket.type.literal(c.storedValue(nodeId, data, socket))
}

/** Emits the node's GLSL and returns its outputs. Only for nodes that run in the shader. */
export function evaluate(c: Compilation, id: string): Record<string, Value> {
  const cached = c.emitted.get(id)
  if (cached) return cached
  const { node, shape } = c.lookup(id)
  if (!shape.exec) throw new GraphError(`${shape.title} runs once per frame and cannot be drawn directly`, id)

  c.enter(id)
  const settled = settledInputs(c, id, shape)
  const resolved = shape.inputs.map((socket) => pixelInput(c, id, node.data, settled, socket))
  const gen = c.widths.get(id)!

  const input: Record<string, unknown> = { ...settled }
  shape.inputs.forEach((socket, i) => {
    if (!isLinkable(socket)) {
      input[socket.name] = resolved[i]
      return
    }
    try {
      const value = socket.type.cast(resolved[i] as Value)
      input[socket.name] = isGenericSocket(socket) ? castTo(value, gen) : value
    } catch (e) {
      throw new GraphError(`${shape.title}: ${(e as Error).message}`, id)
    }
  })

  shape.includes.forEach((chunk) => c.chunks.add(chunk))
  const result = shape.exec(input, context(c, id, gen))
  c.leave(id)
  c.emitted.set(id, result)
  return result
}

/** What `exec` gets on a socket before casting: the settled stream, the linked GLSL value, or the stored value. */
function pixelInput(c: Compilation, id: string, data: GraphNodeData, settled: Record<string, unknown>, socket: InputSocket): unknown {
  if (isStreamSocket(socket)) return settled[socket.name]
  if (isLinkable(socket)) return linkedValue(c, id, data, socket)
  return c.storedValue(id, data, socket)
}

/** The shader text: the chunks the graph used, then mainImage with every emitted line. Returns the node behind each line too. */
export function assemble(c: Compilation): { code: string; lineNodes: (string | null)[] } {
  const library = resolveChunks(c.chunks).flatMap((chunk) => [`// ${chunk.id}`, ...chunk.source.trim().split('\n'), ''])
  const header = ['// Generated by WLEDtoy graph mode', ...library, 'void mainImage(out vec4 c, vec2 uv, float ledIndex) {', '  c = vec4(0.0, 0.0, 0.0, 1.0);']
  return {
    code: [...header, ...c.body.map((l) => `  ${l.text}`), '}', ''].join('\n'),
    lineNodes: [null, ...header.map(() => null), ...c.body.map((l) => l.node), null],
  }
}

/** `chunks` and everything they require, each once, dependencies first. */
function resolveChunks(chunks: Iterable<GlslChunk>): GlslChunk[] {
  const ordered: GlslChunk[] = []
  const visit = (chunk: GlslChunk) => {
    if (ordered.includes(chunk)) return
    chunk.requires.forEach(visit)
    ordered.push(chunk)
  }
  for (const chunk of chunks) visit(chunk)
  return ordered
}
