#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
vec4 globalState[1] = {};
// Generated by WLEDtoy graph mode
void framePass() {
  [[maybe_unused]] float n_n_target = iAudioFeatures[0].x;
  [[maybe_unused]] float n_n_seconds = n_n_target > globalState[0].x ? 0.01 : 0.15;
  globalState[0].x += (n_n_target - globalState[0].x) * (n_n_seconds <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_n_seconds));
  globalState[0].y = globalState[0].x;
}

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  c = vec4(vec3(globalState[0].y), 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  framePass();
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
