// Generated by WLEDtoy graph mode
uniform highp sampler2D iGlobal;
// math:zero:float
float node_zero(float x) { return x == 0.0 ? 1.0 : 0.0; }

// math:pingpong:float
float node_pingpong(float a, float scale) { float z = node_zero(scale); return mix(abs(fract((a - scale) / (scale * 2.0 + z)) * scale * 2.0 - scale), float(0.0), z); }

// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

// color-rgb-to-hsv
vec3 rgb_to_hsv(vec3 rgb)
{
  float cmax, cmin, h, s, v, cdelta;
  vec3 c;

  cmax = max(rgb[0], max(rgb[1], rgb[2]));
  cmin = min(rgb[0], min(rgb[1], rgb[2]));
  cdelta = cmax - cmin;

  v = cmax;

  if (cmax != 0.0) {
    s = cdelta / cmax;
  }
  else {
    s = 0.0;
    h = 0.0;
  }

  if (s == 0.0) {
    h = 0.0;
  }
  else {
    c = (vec3(cmax, cmax, cmax) - rgb) / cdelta;

    if (rgb[0] == cmax) {
      h = c[2] - c[1];
    }
    else if (rgb[1] == cmax) {
      h = 2.0 + c[0] - c[2];
    }
    else {
      h = 4.0 + c[1] - c[0];
    }

    h /= 6.0;

    if (h < 0.0) {
      h += 1.0;
    }
  }

  return vec3(h, s, v);
}

// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

// math:compare:float
float node_compare(float a, float b, float epsilon) { return step(abs(a - b), epsilon); }

// blend-add
vec3 node_mix_add(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col1 + col2, t);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_panels_scaled = uv * vec2(8.0, 3.0);
  vec2 n_panels = fract(n_panels_scaled);
  vec2 n_panels_cell = floor(n_panels_scaled);
  float n_panelIndex = dot(vec3(n_panels_cell, 0.0), vec3(1.0, 1.0, 0.0));
  float n_panelPhase = n_panelIndex + texelFetch(iGlobal, ivec2(1, 0), 0).w;
  float n_panelSelect = node_pingpong(n_panelPhase, 1.0);
  vec3 n_snareLayer = clamp(node_mix_blend(clamp(texelFetch(iGlobal, ivec2(1, 0), 0).x * n_panelSelect, 0.0, 1.0), vec3(0.0, 0.0, 0.0), vec3(0.02, 0.7, 0.85)), 0.0, 1.0);
  float n_rigRotate_a = texelFetch(iGlobal, ivec2(5, 0), 0).x * 6.2831853;
  vec2 n_rigRotate_p = uv - vec2(0.5, 0.5);
  vec2 n_rigRotate = vec2(n_rigRotate_p.x * cos(n_rigRotate_a) + n_rigRotate_p.y * sin(n_rigRotate_a), n_rigRotate_p.y * cos(n_rigRotate_a) - n_rigRotate_p.x * sin(n_rigRotate_a)) + vec2(0.5, 0.5);
  vec2 n_rigMirror_folded = abs(n_rigRotate - vec2(texelFetch(iGlobal, ivec2(6, 0), 0).y)) / max(vec2(texelFetch(iGlobal, ivec2(6, 0), 0).y), 1.0 - vec2(texelFetch(iGlobal, ivec2(6, 0), 0).y));
  vec2 n_rigMirror = vec2(n_rigMirror_folded.x, n_rigRotate.y);
  float n_blocks_n = max(1.0, floor(texelFetch(iGlobal, ivec2(7, 0), 0).y));
  float n_blocks_scaled = clamp(n_rigMirror.x, 0.0, 0.999999) * n_blocks_n;
  float n_blocks_segment = floor(n_blocks_scaled);
  float n_blocks = fract(n_blocks_scaled);
  float n_blocks_fraction = n_blocks_segment / max(1.0, n_blocks_n - 1.0);
  float n_blockRamp_fac = n_blocks_fraction;
  vec3 n_blockRamp = vec3(0.0, 0.75, 1.0);
  n_blockRamp = mix(n_blockRamp, vec3(0.0, 0.3, 1.0), clamp((n_blockRamp_fac - 0.0) / 0.5, 0.0, 1.0));
  n_blockRamp = mix(n_blockRamp, vec3(0.3, 0.05, 1.0), clamp((n_blockRamp_fac - 0.5) / 0.5, 0.0, 1.0));
  vec3 n_blockHue_hsv = rgb_to_hsv(n_blockRamp);
  vec3 n_blockHue = mix(n_blockRamp, max(hsv_to_rgb(vec3(fract(n_blockHue_hsv.x + texelFetch(iGlobal, ivec2(3, 0), 0).y), clamp(n_blockHue_hsv.y * 1.0, 0.0, 1.0), n_blockHue_hsv.z * 1.0)), vec3(0.0)), 1.0);
  float n_blockLit = node_compare(n_blocks_segment, texelFetch(iGlobal, ivec2(8, 0), 0).y, texelFetch(iGlobal, ivec2(8, 0), 0).z);
  float n_blockLevel = mix(texelFetch(iGlobal, ivec2(9, 0), 0).w, texelFetch(iGlobal, ivec2(10, 0), 0).w, clamp(n_blockLit, 0.0, 1.0));
  float n_blockShape_edge = max(0.08, 0.0001) * 0.5;
  float n_blockShape_lo = min(0.06, 0.94);
  float n_blockShape_hi = max(0.06, 0.94);
  float n_blockShape = smoothstep(n_blockShape_lo - n_blockShape_edge, n_blockShape_lo + n_blockShape_edge, n_blocks) * (1.0 - smoothstep(n_blockShape_hi - n_blockShape_edge, n_blockShape_hi + n_blockShape_edge, n_blocks));
  vec3 n_blockLayer = clamp(node_mix_blend(clamp(n_blockLevel * n_blockShape, 0.0, 1.0), n_snareLayer, n_blockHue), 0.0, 1.0);
  float n_hatGlitter = sparkle(ledIndex, 0.15, 6.0);
  vec3 n_hatLayer = clamp(node_mix_add(clamp(texelFetch(iGlobal, ivec2(11, 0), 0).x * n_hatGlitter, 0.0, 1.0), n_blockLayer, n_blockHue), 0.0, 1.0);
  vec3 n_trails = max(n_hatLayer, previousFrame(0.0) * exp(-iTimeDelta / max(iControl[0].z, 0.0001)));
  c = vec4(n_trails, 1.0);
}
