#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
// Generated by WLEDtoy graph mode
// brick-texture
float brick_noise(int ns) {
    int n = (ns + 1013) & 2147483647;
    n = (n >> 13) ^ n;
    int nn = (n * (n * n * 60493 + 19990303) + 1376312589) & 2147483647;
    return 0.5 * (float(nn) / 1073741824.0);
}

float brick(vec3 p,
            float mortar_size,
            float mortar_smooth,
            float bias,
            float brickWidth,
            float row_height,
            float offset_amount,
            int offset_frequency,
            float squash_amount,
            int squash_frequency,
            float& tint) {
    int rownum = int(floor(p.y / row_height));

    float offset = 0.0;
    float current_brick_width = brickWidth;

    if (offset_frequency != 0 && squash_frequency != 0) {
        current_brick_width *= (rownum % squash_frequency) != 0 ? 1.0 : squash_amount;
        offset = (rownum % offset_frequency) != 0 ? 0.0 : (current_brick_width * offset_amount);
    }

    int bricknum = int(floor((p.x + offset) / current_brick_width));

    float x = (p.x + offset) - current_brick_width * float(bricknum);
    float y = p.y - row_height * float(rownum);

    tint = clamp(brick_noise((rownum << 16) + (bricknum & 65535)) + bias, 0.0, 1.0);

    float min_dist = min(min(x, y), min(current_brick_width - x, row_height - y));
    if (min_dist >= mortar_size) {
        return 0.0;
    } else if (mortar_smooth == 0.0) {
        return 1.0;
    } else {
        min_dist = 1.0 - min_dist / mortar_size;
        return smoothstep(0.0, mortar_smooth, min_dist);
    }
}

void brick_texture(
    float offset,
    int offset_frequency,
    float squash,
    int squash_frequency,
    float scale,
    float mortarSize,
    float mortarSmooth,
    float bias,
    float brickWidth,
    float rowHeight,
    vec3 Vector,
    vec3 Color1,
    vec3 Color2,
    vec3 Mortar,
    float& Fac,
    vec3& Color
) {
    vec3 p = Vector;

    float tint = 0.0;
    vec3 col = Color1;

    Fac = brick(p * scale,
                mortarSize,
                mortarSmooth,
                bias,
                brickWidth,
                rowHeight,
                offset,
                offset_frequency,
                squash,
                squash_frequency,
                tint);

    if (Fac != 1.0) {
        col = mix(Color1, Color2, tint);
    }

    Color = mix(col, Mortar, Fac);
}

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  [[maybe_unused]] float n_n_fac; [[maybe_unused]] vec3 n_n_color; brick_texture(0.5, 2, 1.0, 1, 5.0, 0.02, 0.0, 0.0, 0.5, 0.25, vec3(uv, 0.0), vec3(1.0, 1.0, 1.0), vec3(0.0, 0.0, 0.0), vec3(0.67, 0.67, 0.67), n_n_fac, n_n_color);
  c = vec4(vec3(n_n_fac), 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
