// Generated by WLEDtoy graph mode
uniform highp sampler2D iGlobal;
// math:zero:float
float node_zero(float x) { return x == 0.0 ? 1.0 : 0.0; }

// math:divide:float
float node_divide(float a, float b) { float z = node_zero(b); return mix(a / (b + z), float(0.0), z); }

// math:snap:float
float node_snap(float a, float increment) { return floor(node_divide(a, increment)) * increment; }

// color-rgb-to-hsv
vec3 rgb_to_hsv(vec3 rgb)
{
  float cmax, cmin, h, s, v, cdelta;
  vec3 c;

  cmax = max(rgb[0], max(rgb[1], rgb[2]));
  cmin = min(rgb[0], min(rgb[1], rgb[2]));
  cdelta = cmax - cmin;

  v = cmax;

  if (cmax != 0.0) {
    s = cdelta / cmax;
  }
  else {
    s = 0.0;
    h = 0.0;
  }

  if (s == 0.0) {
    h = 0.0;
  }
  else {
    c = (vec3(cmax, cmax, cmax) - rgb) / cdelta;

    if (rgb[0] == cmax) {
      h = c[2] - c[1];
    }
    else if (rgb[1] == cmax) {
      h = 2.0 + c[0] - c[2];
    }
    else {
      h = 4.0 + c[1] - c[0];
    }

    h /= 6.0;

    if (h < 0.0) {
      h += 1.0;
    }
  }

  return vec3(h, s, v);
}

// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_hatSparkle = sparkle(ledIndex, texelFetch(iGlobal, ivec2(0, 0), 0).x, 12.0);
  float n_glintDesaturate = n_hatSparkle * -0.85 + 1.0;
  vec2 n_wheel_p = uv - vec2(0.5, 0.5);
  vec2 n_wheel = vec2(atan(n_wheel_p.y, n_wheel_p.x) / 6.2831853 + 0.5, length(n_wheel_p) * 2.0);
  float n_pumpedRadius = n_wheel.y * texelFetch(iGlobal, ivec2(0, 0), 0).z;
  float n_twistedRadius = n_pumpedRadius * iControl[0].y;
  float n_pinwheelAngle = n_wheel.x * 1.0 + n_twistedRadius;
  float n_spunAngle = n_pinwheelAngle + texelFetch(iGlobal, ivec2(1, 0), 0).z;
  float n_fifthsPosition = fract(n_spunAngle);
  float n_slotBlend_cycle = n_fifthsPosition * 12.0 + 0.0;
  float n_slotBlend_p = fract(n_slotBlend_cycle);
  float n_slotBlend = n_slotBlend_p;
  float n_noteSlot = node_snap(n_fifthsPosition, 0.0833);
  float n_thisNoteStep = n_noteSlot * 7.0 + 0.0417;
  float n_thisNotePosition = fract(n_thisNoteStep);
  float n_thisNoteLevel = chromaAt(1, floor(clamp(n_thisNotePosition, 0.0, 0.9999) * 12.0));
  float n_nextFifthStep = n_noteSlot * 7.0 + 0.625;
  float n_nextFifthPosition = fract(n_nextFifthStep);
  float n_nextFifthLevel = chromaAt(1, floor(clamp(n_nextFifthPosition, 0.0, 0.9999) * 12.0));
  float n_noteGlow = mix(n_thisNoteLevel, n_nextFifthLevel, clamp(n_slotBlend, 0.0, 1.0));
  float n_glowContrast = mix(0.0, texelFetch(iGlobal, ivec2(2, 0), 0).x, clamp((n_noteGlow - texelFetch(iGlobal, ivec2(1, 0), 0).w) / (0.52 - texelFetch(iGlobal, ivec2(1, 0), 0).w), 0.0, 1.0));
  float n_scriabinWheel_fac = n_fifthsPosition;
  vec3 n_scriabinWheel = vec3(1.0, 0.04, 0.0);
  n_scriabinWheel = mix(n_scriabinWheel, vec3(1.0, 0.25, 0.0), clamp((n_scriabinWheel_fac - 0.0) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(1.0, 0.7, 0.0), clamp((n_scriabinWheel_fac - 0.0833) / 0.0834, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(0.15, 1.0, 0.0), clamp((n_scriabinWheel_fac - 0.1667) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(0.0, 1.0, 0.55), clamp((n_scriabinWheel_fac - 0.25) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(0.0, 0.45, 1.0), clamp((n_scriabinWheel_fac - 0.3333) / 0.0834, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(0.05, 0.1, 1.0), clamp((n_scriabinWheel_fac - 0.4167) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(0.4, 0.0, 1.0), clamp((n_scriabinWheel_fac - 0.5) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(0.7, 0.0, 1.0), clamp((n_scriabinWheel_fac - 0.5833) / 0.0834, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(1.0, 0.0, 0.85), clamp((n_scriabinWheel_fac - 0.6667) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(1.0, 0.0, 0.5), clamp((n_scriabinWheel_fac - 0.75) / 0.0833, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(1.0, 0.0, 0.18), clamp((n_scriabinWheel_fac - 0.8333) / 0.0834, 0.0, 1.0));
  n_scriabinWheel = mix(n_scriabinWheel, vec3(1.0, 0.04, 0.0), clamp((n_scriabinWheel_fac - 0.9167) / 0.0833, 0.0, 1.0));
  vec3 n_harmonyColor_hsv = rgb_to_hsv(n_scriabinWheel);
  vec3 n_harmonyColor = mix(n_scriabinWheel, max(hsv_to_rgb(vec3(fract(n_harmonyColor_hsv.x + iControl[0].x), clamp(n_harmonyColor_hsv.y * n_glintDesaturate, 0.0, 1.0), n_harmonyColor_hsv.z * n_glowContrast)), vec3(0.0)), 1.0);
  vec3 n_noteAfterglow = max(n_harmonyColor, previousFrame(0.0) * exp(-iTimeDelta / max(0.5, 0.0001)));
  float n_scope = waveformAt(((1.0 - uv.x) * 0.004 + 0.0) * iAudioHeads.z);
  float n_scopeHeight = n_scope * texelFetch(iGlobal, ivec2(2, 0), 0).z + 0.5;
  float n_scopeOffset = uv.y - n_scopeHeight;
  float n_scopeDistance = abs(n_scopeOffset);
  float n_scopeLine_edge = max(0.03, 0.0001) * 0.5;
  float n_scopeLine = 1.0 - smoothstep(0.045 - n_scopeLine_edge, 0.045 + n_scopeLine_edge, n_scopeDistance);
  vec3 n_scopeCarve = clamp(node_mix_blend(clamp(texelFetch(iGlobal, ivec2(2, 0), 0).y * n_scopeLine, 0.0, 1.0), n_noteAfterglow, vec3(0.0, 0.0, 0.0)), 0.0, 1.0);
  c = vec4(n_scopeCarve, 1.0);
}
