// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_t = clamp(uv.x, 0.0, 1.0);
  float n_n = n_n_t * n_n_t * (3.0 - 2.0 * n_n_t);
  c = vec4(vec3(n_n), 1.0);
}
