#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
vec4 globalState[1] = {};
// Generated by WLEDtoy graph mode
void framePass() {
  if (0.0 >= 0.5 && globalState[0].z < 0.5) globalState[0].x = 1.0;
  if (0.0 < 0.5 && globalState[0].z >= 0.5 && globalState[0].x != 0.0) globalState[0].x = 4.0;
  globalState[0].z = float(0.0 >= 0.5);
  [[maybe_unused]] float n_n_stage = globalState[0].x;
  if (n_n_stage == 1.0) globalState[0].y = min(1.0, globalState[0].y + (0.01 <= 0.0 ? 1.0 : iTimeDelta / 0.01));
  if (n_n_stage == 1.0 && globalState[0].y >= 1.0) globalState[0].x = 2.0;
  if (n_n_stage == 2.0) globalState[0].y = max(0.5, globalState[0].y - (0.2 <= 0.0 ? 1.0 : iTimeDelta / 0.2));
  if (n_n_stage == 2.0 && globalState[0].y <= 0.5) globalState[0].x = 3.0;
  if (n_n_stage == 3.0) globalState[0].y = 0.5;
  if (n_n_stage == 4.0) globalState[0].y = max(0.0, globalState[0].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_n_stage == 4.0 && globalState[0].y <= 0.0) globalState[0].x = 0.0;
  globalState[0].w = globalState[0].y;
}

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  c = vec4(vec3(globalState[0].w), 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  framePass();
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
