#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
// Generated by WLEDtoy graph mode
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

// gradient-texture
// Gradient texture
// Based on https://github.com/blender/blender/blob/8f6af72a3f374a16aab0ec980b5af5ba5a3f442f/intern/cycles/kernel/osl/shaders/node_gradient_texture.osl
// Types:
// 0 = linear, 1 = quadratic, 2 = easing
// 3 = diagonal, 4 = radial, 5 = spherical
// 6 = quadratic_sphere
float gradient(vec3 p, int type) {
  float x, y, z;

  x = p[0];
  y = p[1];
  z = p[2];

  float result = 0.0;

  if (type == 0) {
    result = x;
  }
  else if (type == 1) {
    float r = max(x, 0.0);
    result = r * r;
  }
  else if (type == 2) {
    float r = min(max(x, 0.0), 1.0);
    float t = r * r;

    result = (3.0 * t - 2.0 * t * r);
  }
  else if (type == 3) {
    result = (x + y) * 0.5;
  }
  else if (type == 4) {
    result = atan(y, x) / M_2PI + 0.5;
  }
  else {
    float r = max(1.0 - sqrt(x * x + y * y + z * z), 0.0);

    if (type == 6)
      result = r * r;
    else if (type == 5)
      result = r;
  }

  return clamp(result, 0.0, 1.0);
}

void gradient_texture(
    vec3 Vector,
    int Type,
    float& Fac,
    vec3& Color
) {
    // Gradient texture
    Fac = gradient(Vector, Type);
    Color = vec3(Fac);
}

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  [[maybe_unused]] float n_n_fac; [[maybe_unused]] vec3 n_n_color; gradient_texture(vec3(uv, 0.0), 0, n_n_fac, n_n_color);
  c = vec4(vec3(n_n_fac), 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
