#version 300 es
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

// color-rgb-to-hsv
vec3 rgb_to_hsv(vec3 rgb)
{
  float cmax, cmin, h, s, v, cdelta;
  vec3 c;

  cmax = max(rgb[0], max(rgb[1], rgb[2]));
  cmin = min(rgb[0], min(rgb[1], rgb[2]));
  cdelta = cmax - cmin;

  v = cmax;

  if (cmax != 0.0) {
    s = cdelta / cmax;
  }
  else {
    s = 0.0;
    h = 0.0;
  }

  if (s == 0.0) {
    h = 0.0;
  }
  else {
    c = (vec3(cmax, cmax, cmax) - rgb) / cdelta;

    if (rgb[0] == cmax) {
      h = c[2] - c[1];
    }
    else if (rgb[1] == cmax) {
      h = 2.0 + c[0] - c[2];
    }
    else {
      h = 4.0 + c[1] - c[0];
    }

    h /= 6.0;

    if (h < 0.0) {
      h += 1.0;
    }
  }

  return vec3(h, s, v);
}

// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[1];
  for (int i = 0; i < 1; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  vec3 n_n_hsv = rgb_to_hsv(vec3(1.0, 0.45, 0.1));
  vec3 n_n = mix(vec3(1.0, 0.45, 0.1), max(hsv_to_rgb(vec3(fract(n_n_hsv.x + 0.0), clamp(n_n_hsv.y * 1.0, 0.0, 1.0), n_n_hsv.z * 1.0)), vec3(0.0)), 1.0);
  globalState[0].xyz = n_n;
  outGlobal = texel < 1 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
