#version 300 es
#line 3 1
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// each analysis's own linear spectrum, a row per slot from 0, as levels 0 to 1; iAudioSpectrumBins says how many bins each row holds
uniform highp sampler2D iAudioSpectra;
uniform float iAudioSpectrumBins[4];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

// audio reads
// the Audio node's outputs for the default analysis, in the order of AUDIO_FEATURES, four to a vector
uniform vec4 iAudioFeatures[4];
// slot 0 is the default analysis; graph FFT nodes with other settings use slots 1 and up
float bandsAt(int slot, float x) {
  if (slot == 1) return texture(iAudioBandsExtra[0], vec2(x, 0.25)).r;
  if (slot == 2) return texture(iAudioBandsExtra[1], vec2(x, 0.25)).r;
  if (slot == 3) return texture(iAudioBandsExtra[2], vec2(x, 0.25)).r;
  return texture(iAudioBands, vec2(x, 0.25)).r;
}
int bandCountAt(int slot) {
  if (slot == 1) return textureSize(iAudioBandsExtra[0], 0).x;
  if (slot == 2) return textureSize(iAudioBandsExtra[1], 0).x;
  if (slot == 3) return textureSize(iAudioBandsExtra[2], 0).x;
  return textureSize(iAudioBands, 0).x;
}
// the loudest of the bands that output number band of count covers, as the Bands node folds them
float bandsPeak(int slot, int band, int count) {
  int total = bandCountAt(slot);
  int from = band * total / count;
  int to = max(from + 1, (band + 1) * total / count);
  float peak = 0.0;
  for (int k = from; k < to; k++) peak = max(peak, bandsAt(slot, (float(k) + 0.5) / float(total)));
  return peak;
}
// the loudest bin of an analysis's own spectrum between lo and hi Hz, as the Band Split node reads it: the bins either
// side of the range included, as the frame body it replaced took them
float spectrumPeak(int slot, float lo, float hi) {
  int bins = int(iAudioSpectrumBins[slot]);
  float hz = iAudioHeads.z / (2.0 * float(bins));
  int last = min(bins - 1, int(ceil(max(lo, hi) / hz)));
  float peak = 0.0;
  for (int i = max(1, int(min(lo, hi) / hz)); i <= last; i++) peak = max(peak, texelFetch(iAudioSpectra, ivec2(i, slot), 0).r);
  return peak;
}

// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[12];
  for (int i = 0; i < 12; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  float n_baseDrift_restart = float(0.0 >= 0.5 && globalState[0].y < 0.5);
  globalState[0].y = float(0.0 >= 0.5);
  globalState[0].x = (n_baseDrift_restart > 0.5 ? 0.0 : globalState[0].x) + 0.25 * iTimeDelta;
  globalState[0].z = globalState[0].x;
  float n_padEnv_time = iAudioFeatures[3].y > globalState[0].w ? 0.06 : 0.7;
  globalState[0].w += (iAudioFeatures[3].y - globalState[0].w) * (n_padEnv_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_padEnv_time));
  float n_breathWave_cycle = iTime * 0.25 + 0.5;
  float n_breathWave_p = fract(n_breathWave_cycle);
  float n_breathWave = 0.5 - 0.5 * cos(6.2831853 * n_breathWave_p);
  float n_baseLevel = mix(0.2, n_breathWave, clamp((globalState[0].w - 0.1) / (0.3 - 0.1), 0.0, 1.0));
  globalState[1].x = n_baseLevel;
  globalState[1].y = globalState[1].y > 0.5 ? float(iAudioFeatures[2].w > 0.5) : float(iAudioFeatures[2].w >= 0.8);
  float n_kickPresence_time = globalState[1].y > globalState[1].z ? 0.05 : 0.4;
  globalState[1].z += (globalState[1].y - globalState[1].z) * (n_kickPresence_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_kickPresence_time));
  float n_quietBoost = mix(1.0, 0.2, clamp(globalState[1].z, 0.0, 1.0));
  globalState[1].w = n_quietBoost;
  float n_kickCounter_up = float(globalState[1].y >= 0.5 && globalState[2].y < 0.5);
  globalState[2].y = float(globalState[1].y >= 0.5);
  float n_kickCounter_restart = float(0.0 >= 0.5 && globalState[2].z < 0.5);
  globalState[2].z = float(0.0 >= 0.5);
  if (n_kickCounter_up > 0.5) globalState[2].x = (globalState[2].x + 1.0 - 12.0 * floor((globalState[2].x + 1.0 + 0.5) / 12.0));
  if (n_kickCounter_restart > 0.5) globalState[2].x = 0.0;
  float n_kickCounter_phase = globalState[2].x / 12.0;
  float n_hitRandom = fract(sin(globalState[2].x * 127.1 + 311.7) * 43758.5453);
  float n_hitHue = n_hitRandom * iControl[0].x + n_kickCounter_phase;
  float n_kickToggle_flip = float(globalState[1].y >= 0.5 && globalState[3].x < 0.5);
  globalState[3].x = float(globalState[1].y >= 0.5);
  if (n_kickToggle_flip > 0.5) globalState[2].w = 1.0 - globalState[2].w;
  float n_hueHoldA_rose = float(globalState[2].w >= 0.5 && globalState[3].z < 0.5);
  globalState[3].z = float(globalState[2].w >= 0.5);
  if (n_hueHoldA_rose > 0.5) globalState[3].y = n_hitHue;
  vec3 n_ringColorA = hsv_to_rgb(vec3(globalState[3].y, 1.0, 1.0));
  globalState[4].xyz = n_ringColorA;
  float n_energySum = iAudioFeatures[3].w + iAudioFeatures[3].y;
  float n_energyEnv_time = n_energySum > globalState[4].w ? 0.25 : 0.3;
  globalState[4].w += (n_energySum - globalState[4].w) * (n_energyEnv_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_energyEnv_time));
  float n_ringPower = mix(0.6, 1.0, clamp((globalState[4].w - 0.38) / (0.52 - 0.38), 0.0, 1.0));
  globalState[5].x = n_ringPower;
  float n_ringAgeA_restart = float(globalState[2].w >= 0.5 && globalState[5].z < 0.5);
  globalState[5].z = float(globalState[2].w >= 0.5);
  globalState[5].y = (n_ringAgeA_restart > 0.5 ? 0.0 : globalState[5].y) + iControl[0].y * iTimeDelta;
  globalState[5].w = globalState[5].y;
  if (globalState[1].y >= 0.5 && globalState[6].z < 0.5) globalState[6].x = 1.0;
  globalState[6].z = float(globalState[1].y >= 0.5);
  float n_kickPunch_stage = globalState[6].x;
  if (n_kickPunch_stage == 1.0) globalState[6].y = min(1.0, globalState[6].y + (0.0 <= 0.0 ? 1.0 : iTimeDelta / 0.0));
  if (n_kickPunch_stage == 1.0 && globalState[6].y >= 1.0) globalState[6].x = 2.0;
  if (n_kickPunch_stage == 2.0) globalState[6].y = max(0.0, globalState[6].y - (0.18 <= 0.0 ? 1.0 : iTimeDelta / 0.18));
  if (n_kickPunch_stage == 2.0 && globalState[6].y <= 0.0) globalState[6].x = 0.0;
  if (n_kickPunch_stage == 3.0) globalState[6].y = 0.0;
  if (n_kickPunch_stage == 4.0) globalState[6].y = max(0.0, globalState[6].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_kickPunch_stage == 4.0 && globalState[6].y <= 0.0) globalState[6].x = 0.0;
  float n_ringLead = mix(0.0, -0.18, clamp((globalState[6].y - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  globalState[6].w = n_ringLead;
  float n_ringThickness = mix(0.09, 0.22, clamp((globalState[4].w - 0.38) / (0.52 - 0.38), 0.0, 1.0));
  globalState[7].x = n_ringThickness;
  float n_toggleInverse = 1.0 - globalState[2].w;
  float n_hueHoldB_rose = float(n_toggleInverse >= 0.5 && globalState[7].z < 0.5);
  globalState[7].z = float(n_toggleInverse >= 0.5);
  if (n_hueHoldB_rose > 0.5) globalState[7].y = n_hitHue;
  vec3 n_ringColorB = hsv_to_rgb(vec3(globalState[7].y, 1.0, 1.0));
  globalState[8].xyz = n_ringColorB;
  float n_ringAgeB_restart = float(n_toggleInverse >= 0.5 && globalState[9].x < 0.5);
  globalState[9].x = float(n_toggleInverse >= 0.5);
  globalState[8].w = (n_ringAgeB_restart > 0.5 ? 0.0 : globalState[8].w) + iControl[0].y * iTimeDelta;
  globalState[9].y = globalState[8].w;
  float n_spokeSpin_restart = float(0.0 >= 0.5 && globalState[9].w < 0.5);
  globalState[9].w = float(0.0 >= 0.5);
  globalState[9].z = (n_spokeSpin_restart > 0.5 ? 0.0 : globalState[9].z) + -0.3 * iTimeDelta;
  globalState[9].z = fract(globalState[9].z);
  globalState[10].x = globalState[9].z;
  globalState[10].y = globalState[10].y > 0.5 ? float(iAudioFeatures[3].z > 0.1) : float(iAudioFeatures[3].z >= 0.19);
  if (globalState[10].y >= 0.5 && globalState[11].x < 0.5) globalState[10].z = 1.0;
  globalState[11].x = float(globalState[10].y >= 0.5);
  float n_snareEnv_stage = globalState[10].z;
  if (n_snareEnv_stage == 1.0) globalState[10].w = min(1.0, globalState[10].w + (0.01 <= 0.0 ? 1.0 : iTimeDelta / 0.01));
  if (n_snareEnv_stage == 1.0 && globalState[10].w >= 1.0) globalState[10].z = 2.0;
  if (n_snareEnv_stage == 2.0) globalState[10].w = max(0.0, globalState[10].w - (0.22 <= 0.0 ? 1.0 : iTimeDelta / 0.22));
  if (n_snareEnv_stage == 2.0 && globalState[10].w <= 0.0) globalState[10].z = 0.0;
  if (n_snareEnv_stage == 3.0) globalState[10].w = 0.0;
  if (n_snareEnv_stage == 4.0) globalState[10].w = max(0.0, globalState[10].w - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_snareEnv_stage == 4.0 && globalState[10].w <= 0.0) globalState[10].z = 0.0;
  float n_snareReach = mix(1.55, 0.85, clamp((globalState[10].w - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  globalState[11].y = n_snareReach;
  outGlobal = texel < 12 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
