// Generated by WLEDtoy graph mode
uniform highp sampler2D iGlobal;
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

// noise
// Lattice cells wrap every 256 so the hash argument stays small: sin() of a large float is 0 on some GPUs,
// which painted every negative coordinate one flat value. Wrapping the corners too keeps the seams continuous.
float lattice_hash(float c) { return node_hash(mod(c, 256.0)); }
float lattice_hash(vec2 c) { return node_hash(mod(c, 256.0)); }
float lattice_hash(vec3 c) { return node_hash(dot(mod(c, 256.0), vec3(110, 241, 171))); }

float noise1(float x) {
	float i = floor(x);
	float f = fract(x);
	float u = f * f * (3.0 - 2.0 * f);
	return mix(lattice_hash(i), lattice_hash(i + 1.0), u);
}

float noise2(vec2 x) {
	vec2 i = floor(x);
	vec2 f = fract(x);

	// Four corners in 2D of a tile
	float a = lattice_hash(i);
	float b = lattice_hash(i + vec2(1.0, 0.0));
	float c = lattice_hash(i + vec2(0.0, 1.0));
	float d = lattice_hash(i + vec2(1.0, 1.0));

	vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float noise3(vec3 x) {
	vec3 i = floor(x);
	vec3 f = fract(x);

	vec3 u = f * f * (3.0 - 2.0 * f);
	return mix(mix(mix( lattice_hash(i + vec3(0, 0, 0)), lattice_hash(i + vec3(1, 0, 0)), u.x),
                   mix( lattice_hash(i + vec3(0, 1, 0)), lattice_hash(i + vec3(1, 1, 0)), u.x), u.y),
               mix(mix( lattice_hash(i + vec3(0, 0, 1)), lattice_hash(i + vec3(1, 0, 1)), u.x),
                   mix( lattice_hash(i + vec3(0, 1, 1)), lattice_hash(i + vec3(1, 1, 1)), u.x), u.y), u.z);
}

// GLSL equivalent of noise_fbm
float noise_fbm(vec3 co, float detail, float roughness, float lacunarity, bool use_normalize) {
    vec3 p = co;
    float fscale = 1.0;
    float amp = 1.0;
    float maxamp = 0.0;
    float sum = 0.0;

    // a runtime float as the bound can spin forever on a bad link; 15 octaves is past visible detail
    int octaves = int(clamp(detail, 0.0, 15.0));
    for (int i = 0; i <= octaves; i++) {
        float t = noise3(fscale * p);
        sum += t * amp;
        maxamp += amp;
        amp *= roughness;
        fscale *= lacunarity;
    }

    float rmd = detail - floor(detail);
    if (rmd != 0.0) {
        float t = noise3(fscale * p);
        float sum2 = sum + t * amp;
        return use_normalize ?
               mix(sum / maxamp, sum2 / (maxamp + amp), rmd) :
               mix(sum, sum2, rmd);
    }
    else {
        return use_normalize ? sum / maxamp : sum;
    }
}

// wave-texture
// GLSL wave function
float wave(vec3 p_input,
           int type, // 0: bands, 1: rings
           int bands_direction, // 0: x, 1: y, 2: z, 3: diagonal
           int rings_direction, // 0: x, 1: y, 2: z, 3: spherical
           int profile, // 0: sine, 1: saw, 2: tri
           float distortion,
           float detail,
           float dscale,
           float droughness,
           float phase)
{
    vec3 p = (p_input + 0.000001) * 0.999999;
    float n = 0.0;

    if (type == 0) { // bands
        if (bands_direction == 0) n = p.x * 20.0;
        else if (bands_direction == 1) n = p.y * 20.0;
        else if (bands_direction == 2) n = p.z * 20.0;
        else n = (p.x + p.y + p.z) * 10.0;
    }
    else if (type == 1) { // rings
        vec3 rp = p;
        if (rings_direction == 0) rp.x = 0.0;
        else if (rings_direction == 1) rp.y = 0.0;
        else if (rings_direction == 2) rp.z = 0.0;
        n = length(rp) * 20.0;
    }

    n += phase;

    if (distortion != 0.0) {
        n += distortion * (noise_fbm(p * dscale, detail, droughness, 2.0, true) * 2.0 - 1.0);
    }

    if (profile == 0) { // sine
        return 0.5 + 0.5 * sin(n - 1.57079632679);
    } else if (profile == 1) { // saw
        n /= 6.28318530718;
        return fract(n);
    } else { // tri
        n /= 6.28318530718;
        return abs(fract(n + 0.5) - 0.5) * 2.0;
    }
}

void wave_texture(int type,
                    int bands_direction,
                    int rings_direction,
                    int profile,
                    float scale,
                    float distortion,
                    float detail,
                    float detail_scale,
                    float detail_roughness,
                    float phase_offset,
                    vec3 vector,
                    out float fac,
                    out vec3 color)
{
    vec3 p = vector * scale;
    float n = wave(p, type, bands_direction, rings_direction, profile, distortion, detail, detail_scale, detail_roughness, phase_offset);
    fac = n;
    color = vec3(n);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_zoomMapping_p = (vec3(uv, 0.0) - vec3(0.5, 0.5, 0.0)) * vec3(texelFetch(iGlobal, ivec2(1, 0), 0).z);
  float n_zoomMapping_a = texelFetch(iGlobal, ivec2(1, 0), 0).x * 6.2831853;
  vec3 n_zoomMapping = vec3(n_zoomMapping_p.x * cos(n_zoomMapping_a) + n_zoomMapping_p.y * sin(n_zoomMapping_a), n_zoomMapping_p.y * cos(n_zoomMapping_a) - n_zoomMapping_p.x * sin(n_zoomMapping_a), n_zoomMapping_p.z) + vec3(0.5, 0.5, 0.0) + vec3(0.0, 0.0, 0.0);
  vec3 n_warpCoords = n_zoomMapping + texelFetch(iGlobal, ivec2(2, 0), 0).xyz;
  vec3 n_warpNoise_p = n_warpCoords * 1.8;
  vec3 n_warpNoise_warped = n_warpNoise_p + 0.0 * (vec3(noise3(n_warpNoise_p + 13.5), noise3(n_warpNoise_p), noise3(n_warpNoise_p - 13.5)) * 2.0 - 1.0);
  float n_warpNoise_fac = noise_fbm(n_warpNoise_warped, 1.0, 0.5, 2.0, true);
  vec3 n_warpNoise_color = vec3(n_warpNoise_fac, noise_fbm(n_warpNoise_warped.yxz + 27.1, 1.0, 0.5, 2.0, true), noise_fbm(n_warpNoise_warped.zyx - 41.3, 1.0, 0.5, 2.0, true));
  vec3 n_warpCentered = n_warpNoise_color - vec3(0.5, 0.5, 0.5);
  vec3 n_warpOffset = n_warpCentered * texelFetch(iGlobal, ivec2(2, 0), 0).w;
  vec3 n_warpedCoords = n_zoomMapping + n_warpOffset;
  vec3 n_cellCoords = n_warpedCoords + texelFetch(iGlobal, ivec2(2, 0), 0).xyz;
  vec2 n_cellField_p = n_cellCoords.xy * 3.0;
  vec2 n_cellField_cell = floor(n_cellField_p);
  float n_cellField_best = 8.0; vec2 n_cellField_nearest = n_cellField_cell;
  for (int j = -1; j <= 1; j++) for (int i = -1; i <= 1; i++) {
    vec2 g = n_cellField_cell + vec2(float(i), float(j));
    vec2 o = g + 0.5 + (vec2(node_hash(g), node_hash(g + 19.1)) - 0.5) * 1.0;
    float d = distance(o, n_cellField_p);
    if (d < n_cellField_best) { n_cellField_best = d; n_cellField_nearest = o; }
  }
  float n_cellField_distance = n_cellField_best;
  vec3 n_cellField_color = vec3(node_hash(n_cellField_nearest), node_hash(n_cellField_nearest + 7.7), node_hash(n_cellField_nearest + 13.9));
  vec3 n_cellField_position = vec3(n_cellField_nearest / 3.0, 0.0);
  float n_hueSpread = n_cellField_distance * -0.4 + 0.42;
  float n_huePosition = n_hueSpread + texelFetch(iGlobal, ivec2(3, 0), 0).x;
  vec3 n_nebulaPalette = palette(n_huePosition, vec3(0.5, 0.2, 0.5), vec3(0.5, 0.25, 0.5), vec3(1.0, 1.0, 1.0), vec3(0.22, 0.0, 0.67));
  float n_bandField_fac; vec3 n_bandField_color; wave_texture(0, 3, 0, 0, 1.3, 0.0, 0.0, 1.0, 0.0, texelFetch(iGlobal, ivec2(3, 0), 0).z, n_warpedCoords, n_bandField_fac, n_bandField_color);
  float n_bandMask = smoothstep(texelFetch(iGlobal, ivec2(3, 0), 0).y, 0.78, n_bandField_fac);
  float n_cellGlow = mix(1.0, 0.15, clamp((n_cellField_distance - 0.1) / (texelFetch(iGlobal, ivec2(4, 0), 0).x - 0.1), 0.0, 1.0));
  float n_density = n_bandMask * n_cellGlow;
  float n_brightness = n_density * texelFetch(iGlobal, ivec2(4, 0), 0).y;
  vec3 n_nebulaColor = n_nebulaPalette * vec3(n_brightness);
  vec3 n_swirlTrails = max(n_nebulaColor, previousFrame(1.0) * exp(-iTimeDelta / max(iControl[0].w, 0.0001)));
  c = vec4(n_swirlTrails, 1.0);
}
