#version 300 es
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

// audio reads
// the Audio node's outputs for the default analysis, in the order of AUDIO_FEATURES, four to a vector
uniform vec4 iAudioFeatures[4];
// slot 0 is the default analysis; graph FFT nodes with other settings use slots 1 and up
float bandsAt(int slot, float x) {
  if (slot == 1) return texture(iAudioBandsExtra[0], vec2(x, 0.25)).r;
  if (slot == 2) return texture(iAudioBandsExtra[1], vec2(x, 0.25)).r;
  if (slot == 3) return texture(iAudioBandsExtra[2], vec2(x, 0.25)).r;
  return texture(iAudioBands, vec2(x, 0.25)).r;
}
int bandCountAt(int slot) {
  if (slot == 1) return textureSize(iAudioBandsExtra[0], 0).x;
  if (slot == 2) return textureSize(iAudioBandsExtra[1], 0).x;
  if (slot == 3) return textureSize(iAudioBandsExtra[2], 0).x;
  return textureSize(iAudioBands, 0).x;
}
// the loudest of the bands that output number band of count covers, as the Bands node folds them
float bandsPeak(int slot, int band, int count) {
  int total = bandCountAt(slot);
  int from = band * total / count;
  int to = max(from + 1, (band + 1) * total / count);
  float peak = 0.0;
  for (int k = from; k < to; k++) peak = max(peak, bandsAt(slot, (float(k) + 0.5) / float(total)));
  return peak;
}
// the loudest bin of the default analysis's spectrum between lo and hi Hz, as the Band Split node reads it; the texture's
// bins are coarser than the analysis's, so an edge of the range can take in the rest of its bin
float spectrumPeak(float lo, float hi) {
  int bins = textureSize(iAudio, 0).x;
  float hz = iAudioHeads.z * 0.5 / float(bins);
  int last = min(bins - 1, int(max(lo, hi) / hz));
  float peak = 0.0;
  for (int i = int(min(lo, hi) / hz); i <= last; i++) peak = max(peak, texelFetch(iAudio, ivec2(i, 0), 0).r);
  return peak;
}

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[5];
  for (int i = 0; i < 5; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  float n_airFollower_time = iAudioFeatures[3].w > globalState[0].x ? 0.5 : 0.6;
  globalState[0].x += (iAudioFeatures[3].w - globalState[0].x) * (n_airFollower_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_airFollower_time));
  float n_heat = mix(0.0, 1.0, clamp((globalState[0].x - 0.03) / (0.14 - 0.03), 0.0, 1.0));
  float n_bassFollower_time = iAudioFeatures[2].w > globalState[0].y ? 0.08 : 0.45;
  globalState[0].y += (iAudioFeatures[2].w - globalState[0].y) * (n_bassFollower_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_bassFollower_time));
  float n_bassFlow = globalState[0].y * 0.4 + 0.15;
  float n_heatFlow = n_heat * 0.35 + n_bassFlow;
  float n_flowRate = n_heatFlow * iControl[0].x;
  float n_flowPhase_restart = float(0.0 >= 0.5 && globalState[0].w < 0.5);
  globalState[0].w = float(0.0 >= 0.5);
  globalState[0].z = (n_flowPhase_restart > 0.5 ? 0.0 : globalState[0].z) + n_flowRate * iTimeDelta;
  float n_swirlTurn = globalState[0].z * 0.05;
  globalState[1].x = n_swirlTurn;
  float n_kickShape = mix(0.0, 1.0, clamp((iAudioFeatures[2].w - 0.55) / (1.0 - 0.55), 0.0, 1.0));
  float n_kickPulse_time = n_kickShape > globalState[1].y ? 0.05 : 0.16;
  globalState[1].y += (n_kickShape - globalState[1].y) * (n_kickPulse_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_kickPulse_time));
  float n_kickZoom = globalState[1].y * -0.12 + 1.0;
  globalState[1].z = n_kickZoom;
  vec3 n_flowVector = vec3(globalState[0].z) * vec3(0.3, 0.12, 0.7);
  globalState[2].xyz = n_flowVector;
  float n_warpEnergy = n_heat * 0.6 + 0.45;
  float n_warpKick = globalState[1].y * 0.2 + n_warpEnergy;
  float n_warpStrength = n_warpKick * iControl[0].y;
  globalState[2].w = n_warpStrength;
  float n_heatOffset = n_heat * 0.5 + iControl[0].z;
  globalState[3].x = n_heatOffset;
  float n_bandGap = globalState[0].y * 0.45 + 0.0;
  globalState[3].y = n_bandGap;
  float n_bandPhase = globalState[0].z * 6.0;
  globalState[3].z = n_bandPhase;
  float n_vocalFollower_time = iAudioFeatures[3].y > globalState[3].w ? 0.03 : 0.25;
  globalState[3].w += (iAudioFeatures[3].y - globalState[3].w) * (n_vocalFollower_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_vocalFollower_time));
  float n_cellReach = globalState[3].w * 0.9 + 0.55;
  globalState[4].x = n_cellReach;
  float n_kickLift = globalState[1].y * 0.45 + 0.65;
  globalState[4].y = n_kickLift;
  outGlobal = texel < 5 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
