// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_n = palette(uv.x, vec3(0.5, 0.5, 0.5), vec3(0.5, 0.5, 0.5), vec3(1.0, 1.0, 1.0), vec3(0.0, 0.33, 0.67));
  c = vec4(n_n, 1.0);
}
