#version 300 es
#line 3 1
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// each analysis's own linear spectrum, a row per slot from 0, as levels 0 to 1; iAudioSpectrumBins says how many bins each row holds
uniform highp sampler2D iAudioSpectra;
uniform float iAudioSpectrumBins[4];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

// audio reads
// the Audio node's outputs for the default analysis, in the order of AUDIO_FEATURES, four to a vector
uniform vec4 iAudioFeatures[4];
// slot 0 is the default analysis; graph FFT nodes with other settings use slots 1 and up
float bandsAt(int slot, float x) {
  if (slot == 1) return texture(iAudioBandsExtra[0], vec2(x, 0.25)).r;
  if (slot == 2) return texture(iAudioBandsExtra[1], vec2(x, 0.25)).r;
  if (slot == 3) return texture(iAudioBandsExtra[2], vec2(x, 0.25)).r;
  return texture(iAudioBands, vec2(x, 0.25)).r;
}
int bandCountAt(int slot) {
  if (slot == 1) return textureSize(iAudioBandsExtra[0], 0).x;
  if (slot == 2) return textureSize(iAudioBandsExtra[1], 0).x;
  if (slot == 3) return textureSize(iAudioBandsExtra[2], 0).x;
  return textureSize(iAudioBands, 0).x;
}
// the loudest of the bands that output number band of count covers, as the Bands node folds them
float bandsPeak(int slot, int band, int count) {
  int total = bandCountAt(slot);
  int from = band * total / count;
  int to = max(from + 1, (band + 1) * total / count);
  float peak = 0.0;
  for (int k = from; k < to; k++) peak = max(peak, bandsAt(slot, (float(k) + 0.5) / float(total)));
  return peak;
}
// the loudest bin of an analysis's own spectrum between lo and hi Hz, as the Band Split node reads it: the bins either
// side of the range included, as the frame body it replaced took them
float spectrumPeak(int slot, float lo, float hi) {
  int bins = int(iAudioSpectrumBins[slot]);
  float hz = iAudioHeads.z / (2.0 * float(bins));
  int last = min(bins - 1, int(ceil(max(lo, hi) / hz)));
  float peak = 0.0;
  for (int i = max(1, int(min(lo, hi) / hz)); i <= last; i++) peak = max(peak, texelFetch(iAudioSpectra, ivec2(i, slot), 0).r);
  return peak;
}

// math:compare:float
float node_compare(float a, float b, float epsilon) { return step(abs(a - b), epsilon); }

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[9];
  for (int i = 0; i < 9; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  float n_leadSlow_time = iAudioFeatures[3].y > globalState[0].x ? 0.3 : 0.3;
  globalState[0].x += (iAudioFeatures[3].y - globalState[0].x) * (n_leadSlow_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_leadSlow_time));
  float n_leadTransient = iAudioFeatures[3].y - globalState[0].x;
  float n_kickPresence_time = iAudioFeatures[2].w > globalState[0].y ? 0.0 : 0.6;
  globalState[0].y += (iAudioFeatures[2].w - globalState[0].y) * (n_kickPresence_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_kickPresence_time));
  float n_drumsGone = (1.0 - step(0.15, globalState[0].y));
  float n_dropTension_time = n_drumsGone > globalState[0].z ? 0.7 : 4.0;
  globalState[0].z += (n_drumsGone - globalState[0].z) * (n_dropTension_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_dropTension_time));
  float n_leadSpark = mix(0.0, globalState[0].z, clamp((n_leadTransient - 0.02) / (0.1 - 0.02), 0.0, 1.0));
  float n_sparkDrive = max(iAudioFeatures[3].w, n_leadSpark);
  globalState[0].w = globalState[0].w > 0.5 ? float(n_sparkDrive > 0.09) : float(n_sparkDrive >= 0.15);
  if (globalState[0].w >= 0.5 && globalState[1].z < 0.5) globalState[1].x = 1.0;
  globalState[1].z = float(globalState[0].w >= 0.5);
  float n_sparkFlash_stage = globalState[1].x;
  if (n_sparkFlash_stage == 1.0) globalState[1].y = min(1.0, globalState[1].y + (0.01 <= 0.0 ? 1.0 : iTimeDelta / 0.01));
  if (n_sparkFlash_stage == 1.0 && globalState[1].y >= 1.0) globalState[1].x = 2.0;
  if (n_sparkFlash_stage == 2.0) globalState[1].y = max(0.0, globalState[1].y - (0.22 <= 0.0 ? 1.0 : iTimeDelta / 0.22));
  if (n_sparkFlash_stage == 2.0 && globalState[1].y <= 0.0) globalState[1].x = 0.0;
  if (n_sparkFlash_stage == 3.0) globalState[1].y = 0.0;
  if (n_sparkFlash_stage == 4.0) globalState[1].y = max(0.0, globalState[1].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_sparkFlash_stage == 4.0 && globalState[1].y <= 0.0) globalState[1].x = 0.0;
  globalState[1].w = globalState[1].y;
  float n_sparkSeed_rose = float(globalState[0].w >= 0.5 && globalState[2].y < 0.5);
  globalState[2].y = float(globalState[0].w >= 0.5);
  if (n_sparkSeed_rose > 0.5) globalState[2].x = iTime;
  globalState[2].z = globalState[2].x;
  globalState[2].w = globalState[2].w > 0.5 ? float(iAudioFeatures[2].w > 0.5) : float(iAudioFeatures[2].w >= 0.85);
  float n_alternateKick_flip = float(globalState[2].w >= 0.5 && globalState[3].y < 0.5);
  globalState[3].y = float(globalState[2].w >= 0.5);
  if (n_alternateKick_flip > 0.5) globalState[3].x = 1.0 - globalState[3].x;
  float n_meteorArmed = max(globalState[3].x, globalState[0].z);
  float n_meteorTrigger = globalState[2].w * n_meteorArmed;
  if (n_meteorTrigger >= 0.5 && globalState[4].x < 0.5) globalState[3].z = 1.0;
  globalState[4].x = float(n_meteorTrigger >= 0.5);
  float n_meteorGlow_stage = globalState[3].z;
  if (n_meteorGlow_stage == 1.0) globalState[3].w = min(1.0, globalState[3].w + (0.0 <= 0.0 ? 1.0 : iTimeDelta / 0.0));
  if (n_meteorGlow_stage == 1.0 && globalState[3].w >= 1.0) globalState[3].z = 2.0;
  if (n_meteorGlow_stage == 2.0) globalState[3].w = max(0.0, globalState[3].w - (1.4 <= 0.0 ? 1.0 : iTimeDelta / 1.4));
  if (n_meteorGlow_stage == 2.0 && globalState[3].w <= 0.0) globalState[3].z = 0.0;
  if (n_meteorGlow_stage == 3.0) globalState[3].w = 0.0;
  if (n_meteorGlow_stage == 4.0) globalState[3].w = max(0.0, globalState[3].w - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_meteorGlow_stage == 4.0 && globalState[3].w <= 0.0) globalState[3].z = 0.0;
  globalState[4].y = globalState[3].w;
  if (n_meteorTrigger >= 0.5 && globalState[5].x < 0.5) globalState[4].z = 1.0;
  globalState[5].x = float(n_meteorTrigger >= 0.5);
  float n_meteorFlight_stage = globalState[4].z;
  if (n_meteorFlight_stage == 1.0) globalState[4].w = min(1.0, globalState[4].w + (0.0 <= 0.0 ? 1.0 : iTimeDelta / 0.0));
  if (n_meteorFlight_stage == 1.0 && globalState[4].w >= 1.0) globalState[4].z = 2.0;
  if (n_meteorFlight_stage == 2.0) globalState[4].w = max(0.0, globalState[4].w - (0.68 <= 0.0 ? 1.0 : iTimeDelta / 0.68));
  if (n_meteorFlight_stage == 2.0 && globalState[4].w <= 0.0) globalState[4].z = 0.0;
  if (n_meteorFlight_stage == 3.0) globalState[4].w = 0.0;
  if (n_meteorFlight_stage == 4.0) globalState[4].w = max(0.0, globalState[4].w - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_meteorFlight_stage == 4.0 && globalState[4].w <= 0.0) globalState[4].z = 0.0;
  float n_meteorHead = mix(0.45, 1.5, clamp((globalState[4].w - 1.0) / (0.0 - 1.0), 0.0, 1.0));
  globalState[5].y = n_meteorHead;
  float n_meteorTailEnd = n_meteorHead - 0.07;
  globalState[5].z = n_meteorTailEnd;
  float n_highEnv_time = iAudioFeatures[3].w > globalState[5].w ? 0.02 : 0.4;
  globalState[5].w += (iAudioFeatures[3].w - globalState[5].w) * (n_highEnv_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_highEnv_time));
  globalState[6].x = globalState[5].w;
  float n_barBallistics_time = iAudioFeatures[0].x > globalState[6].y ? 0.015 : 0.28;
  globalState[6].y += (iAudioFeatures[0].x - globalState[6].y) * (n_barBallistics_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_barBallistics_time));
  float n_barGlow = mix(0.35, 1.0, clamp((globalState[6].y - 0.22) / (0.5 - 0.22), 0.0, 1.0));
  globalState[6].z = n_barGlow;
  float n_reach = mix(iControl[0].y, 0.94, clamp((globalState[0].z - 0.0) / (0.8 - 0.0), 0.0, 1.0));
  float n_barLength = globalState[6].y * n_reach;
  globalState[6].w = n_barLength;
  float n_peakHang_above = float(n_barLength >= globalState[7].x);
  globalState[7].y = n_peakHang_above > 0.5 ? 0.0 : globalState[7].y + iTimeDelta;
  if (n_peakHang_above < 0.5 && globalState[7].y > 0.35) globalState[7].x = max(n_barLength, globalState[7].x * exp(-iTimeDelta / max(0.5, 0.0001)));
  if (n_peakHang_above > 0.5) globalState[7].x = n_barLength;
  float n_barAtPeak = node_compare(n_barLength, globalState[7].x, 0.005);
  float n_fallSpeed_restart = float(n_barAtPeak >= 0.5 && globalState[7].w < 0.5);
  globalState[7].w = float(n_barAtPeak >= 0.5);
  globalState[7].z = (n_fallSpeed_restart > 0.5 ? 0.0 : globalState[7].z) + 6.0 * iTimeDelta;
  globalState[8].x += min(1000.0 * iTimeDelta, max(-(globalState[7].z) * iTimeDelta, n_barLength - globalState[8].x));
  globalState[8].y = globalState[8].x;
  float n_peakEdge = globalState[8].x + 0.025;
  globalState[8].z = n_peakEdge;
  outGlobal = texel < 9 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
