// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_n_p = uv - vec2(0.5, 0.5);
  vec2 n_n = vec2(atan(n_n_p.y, n_n_p.x) / 6.2831853 + 0.5, length(n_n_p) * 2.0);
  c = vec4(vec3(n_n, 0.0), 1.0);
}
