#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
// Generated by WLEDtoy graph mode
void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  [[maybe_unused]] float n_n_edge = max(0.0, 0.0001) * 0.5;
  [[maybe_unused]] float n_n_lo = min(0.25, 0.75);
  [[maybe_unused]] float n_n_hi = max(0.25, 0.75);
  [[maybe_unused]] float n_n = smoothstep(n_n_lo - n_n_edge, n_n_lo + n_n_edge, uv.x) * (1.0 - smoothstep(n_n_hi - n_n_edge, n_n_hi + n_n_edge, uv.x));
  c = vec4(vec3(n_n), 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
