// Generated by WLEDtoy graph mode
uniform highp sampler2D iGlobal;
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  c = vec4(vec3(texelFetch(iGlobal, ivec2(0, 0), 0).y), 1.0);
}
