#version 300 es
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[1];
  for (int i = 0; i < 1; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  float n_n_restart = float(0.0 >= 0.5 && globalState[0].z < 0.5);
  globalState[0].z = float(0.0 >= 0.5);
  float n_n_up = (1.0 - n_n_restart) * float(0.0 >= 0.5 && globalState[0].y < 0.5);
  if (n_n_restart < 0.5) globalState[0].y = float(0.0 >= 0.5);
  globalState[0].x = n_n_restart > 0.5 ? 0.0 : globalState[0].x + n_n_up;
  globalState[0].x = (globalState[0].x - 4.0 * floor((globalState[0].x + 0.5) / 4.0));
  float n_n_value = globalState[0].x < 0.5 ? 1.0 : globalState[0].x < 1.5 ? 0.0 : globalState[0].x < 2.5 ? 0.5 : 0.0;
  globalState[0].w = n_n_value;
  outGlobal = texel < 1 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
