#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
// Generated by WLEDtoy graph mode
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  [[maybe_unused]] float n_n_fac = node_hash(vec3(uv, 0.0).xy + vec3(uv, 0.0).z);
  [[maybe_unused]] vec3 n_n = vec3(n_n_fac, node_hash(vec3(uv, 0.0).yz + 17.3 + vec3(uv, 0.0).x), node_hash(vec3(uv, 0.0).zx + 41.7 + vec3(uv, 0.0).y));
  c = vec4(vec3(n_n_fac), 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
