import type { SocketValue } from '@/lib/graph/model/doc'
import { createUsermodCompiler } from '@/lib/graph/compile/compilers'
import { MATH_OPS } from '@/lib/graph/nodes/converter/math'
import { VECTOR_OPS } from '@/lib/graph/nodes/converter/vector-math'
import { listItems, findNodeItem } from '@/lib/graph/registry'
import { placeAlone, graph, node } from './index'
import { MATH_INPUTS, VECTOR_INPUTS } from './parity-inputs'

/** Every kind alone w/ defaults, bar those w/o a C++ twin, which `excluded` names w/ the reason */
export function writeNodesUnit(): { code: string; excluded: string[] } {
  const compiler = createUsermodCompiler(1, { checkInputs: false })
  const units = listItems().map((item) => ({ id: item.id, ...compiler.compile(placeAlone(item)) }))
  const namespaces = units.flatMap(({ id, program }) => (program ? [nestNamespace(program.code, `kind_${id}`)] : []))
  const excluded = units.flatMap(({ id, program, issues }) => (program ? [] : [`${id} (${issues.at(-1)!.message})`]))
  return { code: ['// Generated by scripts/gen-cpp-unit.ts; do not edit.', ...namespaces].join('\n'), excluded }
}

/** Every Math and Vector Math op on fixed stored inputs, beside its op table's `js` for the same inputs */
export function writeParityUnit(): { code: string; ops: string[] } {
  const compiler = createUsermodCompiler(1)
  const ops = [...listMathOps(), ...listVectorOps()].map((op) => ({ ...op, units: op.cases.map(({ values }) => compileCase(compiler, op, values)) }))
  const definitions = ops.flatMap((op) => op.units.map((unit, i) => nestNamespace(unit, toCaseNamespace(op, i))))
  const code = [
    '// Generated by scripts/gen-cpp-unit.ts; do not edit.',
    '#include "parity.h"',
    '',
    ...definitions,
    ...ops.flatMap(tabulateOp),
    ...declareMain(ops),
  ]
  return { code: code.join('\n'), ops: ops.map((op) => op.name) }
}

interface ParityOp {
  name: string
  kind: string
  cases: { values: Record<string, SocketValue>; want: number[] }[]
}

function listMathOps(): ParityOp[] {
  return Object.entries(MATH_OPS).map(([op, definition]) => ({
    name: `math.${op}`,
    kind: 'math',
    cases: MATH_INPUTS.map(([a, b, c]) => ({ values: keepSockets('math', { op, a, b, c }), want: [definition.js(a, b, c)] })),
  }))
}

// Reflect normalizes `b`; GLSL's normalize of zero is undefined where the reference's is 0
function listVectorOps(): ParityOp[] {
  return Object.entries(VECTOR_OPS).map(([op, definition]) => ({
    name: `vectorMath.${op}`,
    kind: 'vectorMath',
    cases: VECTOR_INPUTS.filter(({ b }) => op !== 'reflect' || b.some((component) => component !== 0)).map(({ a, b, c, scale }) => {
      const want = definition.js(a, b, c, scale)
      return { values: keepSockets('vectorMath', { op, a, b, c, scale }), want: Array.isArray(want) ? want : [want] }
    }),
  }))
}

function compileCase(compiler: ReturnType<typeof createUsermodCompiler>, op: ParityOp, values: Record<string, SocketValue>): string {
  const doc = graph([node('n', op.kind, values), node('o', 'output')], [[`n.${findNodeItem(op.kind)!.shape(values).outputs[0].name}`, 'o.color']])
  const { program, issues } = compiler.compile(doc)
  if (!program) throw new Error(`${op.name}: ${issues.map((issue) => issue.message).join('; ')}`)
  return program.code
}

// Own namespace per program, since two kinds including one chunk would define it twice; include guard makes the repeat harmless
function nestNamespace(unit: string, name: string): string {
  if (!unit.includes('\nnamespace wledtoy {\n')) throw new Error('A usermod unit opens namespace wledtoy')
  return unit.replace('\nnamespace wledtoy {\n', `\nnamespace wledtoy::${name} {\n`)
}

function tabulateOp(op: ParityOp & { units: string[] }): string[] {
  const rows = op.cases.map(({ values, want }, i) => {
    const inputs = JSON.stringify(Object.fromEntries(Object.entries(values).filter(([name]) => name !== 'op')))
    const unit = `wledtoy::${toCaseNamespace(op, i)}`
    // Unit defines framePass only w/ global state
    const frame = op.units[i].includes('void framePass()') ? `${unit}::framePass` : 'nullptr'
    return `  {${JSON.stringify(inputs)}, ${frame}, ${unit}::mainImage, ${want.length}, {${want.map(toCppDouble).join(', ')}}},`
  })
  return [`const ParityCase ${toTableName(op)}[] = {`, ...rows, '};', '']
}

function declareMain(ops: ParityOp[]): string[] {
  const rows = ops.map((op) => `  {"${op.name}", ${toTableName(op)}, ${op.cases.length}},`)
  return ['const ParityOp ops[] = {', ...rows, '};', '', `int main() { return runParity(ops, ${ops.length}); }`, '']
}

/** Only values the op has sockets for: unary Math takes no `b` */
function keepSockets(kind: string, values: Record<string, SocketValue>): Record<string, SocketValue> {
  const shape = findNodeItem(kind)!.shape(values)
  return Object.fromEntries(shape.inputs.filter((socket) => socket.name in values).map((socket) => [socket.name, values[socket.name]]))
}

const toTableName = (op: ParityOp) => op.name.replace('.', '_')
const toCaseNamespace = (op: ParityOp, i: number) => `${toTableName(op)}_${i}`

function toCppDouble(value: number): string {
  if (!Number.isFinite(value)) throw new Error(`A parity input gives ${value} in JavaScript; pick inputs with a finite result`)
  return String(value)
}
