import { FPS } from './offline'

// Host side of a usermod: per stdin line, fills the audio arrays, pushes a history row per slot and the samples,
// renders at that time w/ iTimeDelta 1 / FPS, prints LED bytes
export const USERMOD_MAIN = [
  '#include <cstdio>',
  '',
  'namespace host {',
  'bool read(float* values, int count) {',
  '  for (int i = 0; i < count; i++) if (std::scanf("%f", &values[i]) != 1) return false;',
  '  return true;',
  '}',
  'void pushRow(float (*rows)[wledtoy::audioBands], float& head, const float* bands) {',
  '  head = float((int(head) + 1) % wledtoy::audioHistoryRows);',
  '  for (int i = 0; i < wledtoy::audioBands; i++) rows[int(head)][i] = bands[i];',
  '}',
  '}',
  '',
  'int main() {',
  '  using namespace wledtoy;',
  `  iTimeDelta = 1.0f / ${FPS}.0f;`,
  '  static vec3 colors[ledCount];',
  '  float time, sampleRate;',
  '  int samples;',
  '  for (int frame = 0; std::scanf("%f %f", &time, &sampleRate) == 2; frame++) {',
  '    if (!host::read(iAudioBands, audioBands)) return 1;',
  '    for (float* bands : iAudioBandsExtra) if (!host::read(bands, audioBands)) return 1;',
  '    for (vec4& features : iAudioFeatures) if (!host::read(features.c, 4)) return 1;',
  '    for (int slot = 0; slot <= audioExtraSlots; slot++) {',
  '      if (std::scanf("%d", &iAudioSpectrumBins[slot]) != 1 || iAudioSpectrumBins[slot] > audioSpectrumBins) return 1;',
  '      if (!host::read(iAudioSpectra[slot], iAudioSpectrumBins[slot])) return 1;',
  '    }',
  '    if (std::scanf("%d", &samples) != 1) return 1;',
  '    for (int i = 0; i < samples; i++, iAudioHeads.y = float((int(iAudioHeads.y) + 1) % audioWaveSamples)) {',
  '      if (!host::read(&iAudioWave[int(iAudioHeads.y)], 1)) return 1;',
  '    }',
  '    host::pushRow(iAudioHistory, iAudioHeads.x, iAudioBands);',
  '    for (int slot = 0; slot < audioExtraSlots; slot++) host::pushRow(iAudioHistoryExtra[slot], iAudioHistoryHeadExtra[slot], iAudioBandsExtra[slot]);',
  '    iAudioHeads.z = sampleRate;',
  '    renderFrame(time, frame, colors);',
  '    for (const vec3& c : colors) std::printf("%d %d %d ", int(c.x * 255.0f + 0.5f), int(c.y * 255.0f + 0.5f), int(c.z * 255.0f + 0.5f));',
  '    std::printf("\\n");',
  '  }',
  '}',
  '',
]
