// The GLSL target: the pixel pass as the shader the renderer draws per pixel, and the frame pass as the shader that
// draws global state once per LED tick. A graph with no global state has no frame pass, and its pixel pass is exactly
// what the old pipeline emitted.
import type { OutputSettings } from '@/lib/engine/output/output'
import type { FrameSource } from '@/lib/engine/render/frame-pass'
import { PRELUDE_UNIFORMS } from '@/lib/shader/prelude'
import type { GlslChunk } from '@/lib/graph/define/context'
import { glslForm } from '@/lib/graph/compile/glsl/glsl-types'
import { stateLoads, stateTargets } from '@/lib/graph/compile/glsl/glsl-state'
import { resolveChunks } from '@/lib/graph/compile/glsl/glsl'
import type { CompileContext, Slots, Target } from '@/lib/graph/compile/next/context'
import { emitPass, type PassCode, type Spelling } from '@/lib/graph/compile/next/emit'

export const glsl = (): Target<GlslProgram> => ({
  name: 'glsl',
  reads: ['width', 'pass', 'state', 'resources'],
  emit: (ctx) => {
    const texels = vectorsReached(ctx.slots.global)
    const pixel = emitPass(ctx, GLSL, 'pixel')
    const probed = probes(ctx)
    const frame = texels > 0 ? { code: frameShader(emitPass(ctx, GLSL, 'frame'), texels), texels, probes: Object.values(probed).map((offset) => Math.floor(offset / 4)) } : null
    return {
      pixel: pixelShader(ctx, pixel, { chunks: pixel.chunks, globals: texels > 0 ? ['uniform highp sampler2D iGlobal;'] : [], beforeMain: [] }),
      frame,
      probes: probed,
      resources: ctx.resources,
      output: ctx.settings,
    }
  },
})

export interface GlslProgram {
  /** The shader drawn per pixel, `mainImage` as the prelude calls it. */
  pixel: string
  /** The whole shader drawn once per LED tick into global state, as `renderer.compile` takes it; null without global state. */
  frame: FrameSource | null
  /** The global state float each probe node's output is written to, by node id, in the order `frame.probes` lists their texels. */
  probes: Record<string, number>
  /** What nodes registered while compiling, by kind. */
  resources: Record<string, unknown[]>
  /** Wire settings from the graph's Output node. */
  output: OutputSettings | null
}

// the frame pass keeps global state in a local array loaded from last tick's texture; the pixel pass samples the texture
const GLSL: Spelling = {
  form: glslForm,
  globalSlot: (offset, dim, pass) => `${pass === 'frame' ? `globalState[${Math.floor(offset / 4)}]` : `texelFetch(iGlobal, ivec2(${Math.floor(offset / 4)}, 0), 0)`}.${components(offset, dim)}`,
}

export const components = (offset: number, dim: number) => 'xyzw'.slice(offset % 4, (offset % 4) + dim)

/** Pixel state layers or global state texels a table reaches: a slot never straddles two, so its first float says which it is in. */
export function vectorsReached(table: Record<string, Slots>): number {
  const offsets = Object.values(table).flatMap((slots) => Object.values(slots).map((slot) => slot.offset))
  return offsets.reduce((count, offset) => Math.max(count, Math.floor(offset / 4) + 1), 0)
}

/**
 * The old pipeline's shader text: the state targets, `globals`, the chunks, `beforeMain`, then mainImage with every
 * pixel line. The usermod target passes the frame pass as `beforeMain`, so both passes share one set of chunks.
 */
export function pixelShader(ctx: CompileContext, code: PassCode, extra: { chunks: Iterable<GlslChunk>; globals: string[]; beforeMain: string[] }): string {
  const layers = vectorsReached(ctx.slots.pixel)
  const header = ['// Generated by WLEDtoy graph mode', ...stateTargets(layers), ...extra.globals, ...library(extra.chunks), ...extra.beforeMain, 'void mainImage(out vec4 c, vec2 uv, float ledIndex) {', '  c = vec4(0.0, 0.0, 0.0, 1.0);', ...stateLoads(layers)]
  return [...header, ...code.lines.map((l) => `  ${l.text}`), '}', ''].join('\n')
}

export const library = (chunks: Iterable<GlslChunk>) => resolveChunks(chunks).flatMap((chunk) => [`// ${chunk.id}`, ...chunk.source.trim().split('\n'), ''])

/**
 * A whole fragment shader, one fragment per texel: it loads global state, runs the frame bodies, and writes its own
 * texel. Texels past the program's keep what they held, so the renderer can draw more than the program uses.
 */
function frameShader(code: PassCode, texels: number): string {
  return [
    '#version 300 es',
    '// Generated by WLEDtoy graph mode: frame pass',
    'precision highp float;',
    '',
    PRELUDE_UNIFORMS,
    'uniform highp sampler2D iGlobal;',
    'out vec4 outGlobal;',
    '',
    ...library(code.chunks),
    'void main() {',
    '  int texel = int(gl_FragCoord.x);',
    `  vec4 globalState[${texels}];`,
    `  for (int i = 0; i < ${texels}; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);`,
    ...code.lines.map((l) => `  ${l.text}`),
    `  outGlobal = texel < ${texels} ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);`,
    '}',
    '',
  ].join('\n')
}

function probes(ctx: CompileContext): Record<string, number> {
  const probing = ctx.order.filter((id) => ctx.nodes[id].shape.probe)
  return Object.fromEntries(probing.map((id) => [id, ctx.nodes[id].exports![ctx.nodes[id].shape.probe!]]))
}
