// One C++ translation unit holding every node kind alone with its defaults, as the GLSL backend emits it in standalone
// mode. CI compiles it against cpp/wledtoy.h, so a pixel body that leaks a GLSL-only construct fails the build.
import type { NodeItem } from '@/lib/graph/define/shape'
import { allItems } from '@/lib/graph/registry'
import { alone } from '@/lib/graph/testing'
import { buildProgram } from '@/lib/graph/compile/compile'
import { pixelDefinitions } from './cpp'
import { glsl } from '@/lib/graph/compile/glsl/glsl'

export function cppUnit(items: readonly NodeItem[] = allItems()): CppUnit {
  const kinds = items.map((item) => ({ id: item.id, ...standaloneCode(item) }))
  // each kind gets a namespace of its own: two kinds that include the same chunk would otherwise define it twice
  const namespaces = kinds.filter((kind) => !kind.glslOnly).map((kind) => `namespace kind_${kind.id} {\n${kind.code}}\n`)
  const code = ['// Generated by scripts/gen-cpp-unit.ts; do not edit.', '#include "../wledtoy.h"', '', 'namespace wledtoy {', '', ...namespaces, '}', '']
  return { code: code.join('\n'), excluded: kinds.filter((kind) => kind.glslOnly).map((kind) => kind.id) }
}

export interface CppUnit {
  code: string
  /** Kinds whose pixel body declared `ctx.require('glsl')`, so the unit leaves them out. */
  excluded: string[]
}

// the pixel side of cppDefinitions only: a kind with a frame step is still in the unit, since it checks pixel bodies.
// Without pixel state nothing reads ledCount, so it is marked to keep -Werror quiet.
function standaloneCode(item: NodeItem): { code: string; glslOnly: boolean } {
  const program = buildProgram(alone(item), { standalone: true, controls: () => 0.5 })
  const { code, error } = glsl(program)
  if (error) throw new Error(`${item.id}: ${error}`)
  return { code: ['[[maybe_unused]] constexpr int ledCount = 1;', ...pixelDefinitions(program, code)].join('\n'), glslOnly: program.nodes.n?.requires?.includes('glsl') ?? false }
}
