#version 300 es
#line 3 1
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// each analysis's own linear spectrum, a row per slot from 0, as levels 0 to 1; iAudioSpectrumBins says how many bins each row holds
uniform highp sampler2D iAudioSpectra;
uniform float iAudioSpectrumBins[4];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

// audio reads
// the Audio node's outputs for the default analysis, in the order of AUDIO_FEATURES, four to a vector
uniform vec4 iAudioFeatures[4];
// slot 0 is the default analysis; graph FFT nodes with other settings use slots 1 and up
float bandsAt(int slot, float x) {
  if (slot == 1) return texture(iAudioBandsExtra[0], vec2(x, 0.25)).r;
  if (slot == 2) return texture(iAudioBandsExtra[1], vec2(x, 0.25)).r;
  if (slot == 3) return texture(iAudioBandsExtra[2], vec2(x, 0.25)).r;
  return texture(iAudioBands, vec2(x, 0.25)).r;
}
int bandCountAt(int slot) {
  if (slot == 1) return textureSize(iAudioBandsExtra[0], 0).x;
  if (slot == 2) return textureSize(iAudioBandsExtra[1], 0).x;
  if (slot == 3) return textureSize(iAudioBandsExtra[2], 0).x;
  return textureSize(iAudioBands, 0).x;
}
// the loudest of the bands that output number band of count covers, as the Bands node folds them
float bandsPeak(int slot, int band, int count) {
  int total = bandCountAt(slot);
  int from = band * total / count;
  int to = max(from + 1, (band + 1) * total / count);
  float peak = 0.0;
  for (int k = from; k < to; k++) peak = max(peak, bandsAt(slot, (float(k) + 0.5) / float(total)));
  return peak;
}
// the loudest bin of an analysis's own spectrum between lo and hi Hz, as the Band Split node reads it: the bins either
// side of the range included, as the frame body it replaced took them
float spectrumPeak(int slot, float lo, float hi) {
  int bins = int(iAudioSpectrumBins[slot]);
  float hz = iAudioHeads.z / (2.0 * float(bins));
  int last = min(min(bins, textureSize(iAudioSpectra, 0).x) - 1, int(ceil(max(lo, hi) / hz)));
  float peak = 0.0;
  for (int i = max(1, int(min(lo, hi) / hz)); i <= last; i++) peak = max(peak, texelFetch(iAudioSpectra, ivec2(i, slot), 0).r);
  return peak;
}

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[1];
  for (int i = 0; i < 1; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  float n_n = spectrumPeak(0, 60.0, 150.0);
  globalState[0].x = n_n;
  outGlobal = texel < 1 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
