// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_band1 = bandsPeak(0, 0, 8);
  float n_n_band2 = bandsPeak(0, 1, 8);
  float n_n_band3 = bandsPeak(0, 2, 8);
  float n_n_band4 = bandsPeak(0, 3, 8);
  float n_n_band5 = bandsPeak(0, 4, 8);
  float n_n_band6 = bandsPeak(0, 5, 8);
  float n_n_band7 = bandsPeak(0, 6, 8);
  float n_n_band8 = bandsPeak(0, 7, 8);
  c = vec4(vec3(n_n_band1), 1.0);
}
