#version 300 es
#line 3 1
// Generated by WLEDtoy graph mode: frame pass
precision highp float;

uniform vec3  iResolution;
uniform float iTime;
uniform int   iFrame;
uniform float iLedCount;
uniform float iScanY;
uniform sampler2D iAudio;
uniform sampler2D iImage;
// the images a graph's Image Texture nodes use, one layer each, all resampled to one size
uniform highp sampler2DArray iImages;
// row 0: band levels (log or mel spaced), row 1: the 12 pitch classes from C
uniform sampler2D iAudioBands;
// one row of bands per analysis hop, a ring; iAudioHeads.x is the newest row
uniform sampler2D iAudioHistory;
// the same two textures for the extra FFT nodes of a graph (slots 1 and up), and the newest history row of each
uniform sampler2D iAudioBandsExtra[3];
uniform sampler2D iAudioHistoryExtra[3];
uniform float iAudioHistoryHeadExtra[3];
// each analysis's own linear spectrum, a row per slot from 0, as levels 0 to 1; iAudioSpectrumBins says how many bins each row holds
uniform highp sampler2D iAudioSpectra;
uniform float iAudioSpectrumBins[4];
// recent samples, a ring in row-major order; iAudioHeads.y is the next sample to be written, .z the sample rate
uniform sampler2D iAudioWave;
uniform vec3 iAudioHeads;
// x, y, z and segment index of every LED in wire order; iLayoutCount is 0 when the LEDs are a plain strip
uniform sampler2D iLayout;
uniform float iLayoutCount;
// what this pass drew last time: one texel per LED in the LED pass, the whole picture in the preview
uniform sampler2D iPrevFrame;
// seconds since this pass last drew
uniform float iTimeDelta;
// per-frame values computed on the CPU by graph mode; slot k is iControl[k / 4][k % 4]
uniform vec4 iControl[64];
uniform highp sampler2D iGlobal;
out vec4 outGlobal;

// audio reads
// the Audio node's outputs for the default analysis, in the order of AUDIO_FEATURES, four to a vector
uniform vec4 iAudioFeatures[4];
// slot 0 is the default analysis; graph FFT nodes with other settings use slots 1 and up
float bandsAt(int slot, float x) {
  if (slot == 1) return texture(iAudioBandsExtra[0], vec2(x, 0.25)).r;
  if (slot == 2) return texture(iAudioBandsExtra[1], vec2(x, 0.25)).r;
  if (slot == 3) return texture(iAudioBandsExtra[2], vec2(x, 0.25)).r;
  return texture(iAudioBands, vec2(x, 0.25)).r;
}
int bandCountAt(int slot) {
  if (slot == 1) return textureSize(iAudioBandsExtra[0], 0).x;
  if (slot == 2) return textureSize(iAudioBandsExtra[1], 0).x;
  if (slot == 3) return textureSize(iAudioBandsExtra[2], 0).x;
  return textureSize(iAudioBands, 0).x;
}
// the loudest of the bands that output number band of count covers, as the Bands node folds them
float bandsPeak(int slot, int band, int count) {
  int total = bandCountAt(slot);
  int from = band * total / count;
  int to = max(from + 1, (band + 1) * total / count);
  float peak = 0.0;
  for (int k = from; k < to; k++) peak = max(peak, bandsAt(slot, (float(k) + 0.5) / float(total)));
  return peak;
}
// the loudest bin of an analysis's own spectrum between lo and hi Hz, as the Band Split node reads it: the bins either
// side of the range included, as the frame body it replaced took them
float spectrumPeak(int slot, float lo, float hi) {
  int bins = int(iAudioSpectrumBins[slot]);
  float hz = iAudioHeads.z / (2.0 * float(bins));
  int last = min(min(bins, textureSize(iAudioSpectra, 0).x) - 1, int(ceil(max(lo, hi) / hz)));
  float peak = 0.0;
  for (int i = max(1, int(min(lo, hi) / hz)); i <= last; i++) peak = max(peak, texelFetch(iAudioSpectra, ivec2(i, slot), 0).r);
  return peak;
}

// math:zero:float
float node_zero(float x) { return x == 0.0 ? 1.0 : 0.0; }

// math:modulo:float
float node_modulo(float a, float b) { float z = node_zero(b); return mix(a - b * trunc(a / (b + z)), float(0.0), z); }

void main() {
  int texel = int(gl_FragCoord.x);
  vec4 globalState[12];
  for (int i = 0; i < 12; i++) globalState[i] = texelFetch(iGlobal, ivec2(i, 0), 0);
  float n_snareBand = spectrumPeak(1, 2500.0, 4500.0);
  globalState[0].x = globalState[0].x > 0.5 ? float(n_snareBand > 0.13) : float(n_snareBand >= 0.24);
  if (globalState[0].x >= 0.5 && globalState[0].w < 0.5) globalState[0].y = 1.0;
  globalState[0].w = float(globalState[0].x >= 0.5);
  float n_snareFlash_stage = globalState[0].y;
  if (n_snareFlash_stage == 1.0) globalState[0].z = min(1.0, globalState[0].z + (0.01 <= 0.0 ? 1.0 : iTimeDelta / 0.01));
  if (n_snareFlash_stage == 1.0 && globalState[0].z >= 1.0) globalState[0].y = 2.0;
  if (n_snareFlash_stage == 2.0) globalState[0].z = max(0.0, globalState[0].z - (0.25 <= 0.0 ? 1.0 : iTimeDelta / 0.25));
  if (n_snareFlash_stage == 2.0 && globalState[0].z <= 0.0) globalState[0].y = 0.0;
  if (n_snareFlash_stage == 3.0) globalState[0].z = 0.0;
  if (n_snareFlash_stage == 4.0) globalState[0].z = max(0.0, globalState[0].z - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_snareFlash_stage == 4.0 && globalState[0].z <= 0.0) globalState[0].y = 0.0;
  globalState[1].x = globalState[0].z;
  float n_snareSide_flip = float(globalState[0].x >= 0.5 && globalState[1].z < 0.5);
  globalState[1].z = float(globalState[0].x >= 0.5);
  if (n_snareSide_flip > 0.5) globalState[1].y = 1.0 - globalState[1].y;
  globalState[1].w = globalState[1].y;
  float n_kickBand = spectrumPeak(0, 40.0, 130.0);
  float n_drumsOn_above = float(n_kickBand >= globalState[2].x);
  globalState[2].y = n_drumsOn_above > 0.5 ? 0.0 : globalState[2].y + iTimeDelta;
  if (n_drumsOn_above < 0.5 && globalState[2].y > 0.6) globalState[2].x = max(n_kickBand, globalState[2].x * exp(-iTimeDelta / max(0.15, 0.0001)));
  if (n_drumsOn_above > 0.5) globalState[2].x = n_kickBand;
  float n_hatBand = spectrumPeak(1, 9000.0, 16000.0);
  float n_hatOnly = clamp(n_snareBand * -1.1 + n_hatBand, 0.0, 1.0);
  float n_hatDensity_time = n_hatOnly > globalState[2].z ? 0.25 : 0.6;
  globalState[2].z += (n_hatOnly - globalState[2].z) * (n_hatDensity_time <= 0.0 ? 1.0 : 1.0 - exp(-iTimeDelta / n_hatDensity_time));
  globalState[2].w = globalState[2].w > 0.5 ? float(globalState[2].z > 0.038) : float(globalState[2].z >= 0.05);
  globalState[3].x += min(4.0 * iTimeDelta, max(-(2.0) * iTimeDelta, globalState[2].w - globalState[3].x));
  float n_dropHue = globalState[3].x * 0.185 + iControl[0].x;
  float n_heatShift = globalState[2].x * 0.2 + n_dropHue;
  globalState[3].y = n_heatShift;
  float n_beatGate = (1.0 - step(0.5, iAudioFeatures[1].z));
  float n_barClock_restart = float(0.0 >= 0.5 && globalState[4].x < 0.5);
  globalState[4].x = float(0.0 >= 0.5);
  if (n_barClock_restart > 0.5) globalState[3].z = 0.0;
  float n_barClock_up = float(n_beatGate >= 0.5 && globalState[3].w < 0.5);
  globalState[3].w = float(n_beatGate >= 0.5);
  float n_barClock_fired = n_barClock_up * float(globalState[3].z == 0.0);
  if (n_barClock_up > 0.5) globalState[3].z = (globalState[3].z + 1.0 - 4.0 * floor((globalState[3].z + 1.0 + 0.5) / 4.0));
  float n_barClock_phase = globalState[3].z / 4.0;
  float n_angleSeq_restart = float(0.0 >= 0.5 && globalState[4].w < 0.5);
  globalState[4].w = float(0.0 >= 0.5);
  float n_angleSeq_up = (1.0 - n_angleSeq_restart) * float(n_barClock_fired >= 0.5 && globalState[4].z < 0.5);
  if (n_angleSeq_restart < 0.5) globalState[4].z = float(n_barClock_fired >= 0.5);
  globalState[4].y = n_angleSeq_restart > 0.5 ? 0.0 : globalState[4].y + n_angleSeq_up;
  globalState[4].y = (globalState[4].y - 4.0 * floor((globalState[4].y + 0.5) / 4.0));
  float n_angleSeq_value = globalState[4].y < 0.5 ? 0.0 : globalState[4].y < 1.5 ? 0.0 : globalState[4].y < 2.5 ? 0.125 : 0.5;
  globalState[5].x = n_angleSeq_value;
  float n_mirrorSeq_restart = float(0.0 >= 0.5 && globalState[5].w < 0.5);
  globalState[5].w = float(0.0 >= 0.5);
  float n_mirrorSeq_up = (1.0 - n_mirrorSeq_restart) * float(n_barClock_fired >= 0.5 && globalState[5].z < 0.5);
  if (n_mirrorSeq_restart < 0.5) globalState[5].z = float(n_barClock_fired >= 0.5);
  globalState[5].y = n_mirrorSeq_restart > 0.5 ? 0.0 : globalState[5].y + n_mirrorSeq_up;
  globalState[5].y = (globalState[5].y - 4.0 * floor((globalState[5].y + 0.5) / 4.0));
  float n_mirrorSeq_value = globalState[5].y < 0.5 ? 0.5 : globalState[5].y < 1.5 ? 0.5 : globalState[5].y < 2.5 ? 0.0 : 0.0;
  globalState[6].x += min(2.0 * iTimeDelta, max(-(2.0) * iTimeDelta, n_mirrorSeq_value - globalState[6].x));
  globalState[6].y = globalState[6].x;
  float n_blockCountSeq_restart = float(0.0 >= 0.5 && globalState[7].x < 0.5);
  globalState[7].x = float(0.0 >= 0.5);
  float n_blockCountSeq_up = (1.0 - n_blockCountSeq_restart) * float(n_barClock_fired >= 0.5 && globalState[6].w < 0.5);
  if (n_blockCountSeq_restart < 0.5) globalState[6].w = float(n_barClock_fired >= 0.5);
  globalState[6].z = n_blockCountSeq_restart > 0.5 ? 0.0 : globalState[6].z + n_blockCountSeq_up;
  globalState[6].z = (globalState[6].z - 4.0 * floor((globalState[6].z + 0.5) / 4.0));
  float n_blockCountSeq_value = globalState[6].z < 0.5 ? 8.0 : globalState[6].z < 1.5 ? 4.0 : globalState[6].z < 2.5 ? 2.0 : 4.0;
  globalState[7].y = n_blockCountSeq_value;
  float n_eighthGate_cycle = iAudioFeatures[1].z * 2.0 + 0.0;
  float n_eighthGate_p = fract(n_eighthGate_cycle);
  float n_eighthGate = step(n_eighthGate_p, 0.5);
  float n_stepClock = mix(n_beatGate, n_eighthGate, step(0.5, globalState[3].x));
  float n_stepCounter_up = float(n_stepClock >= 0.5 && globalState[7].w < 0.5);
  globalState[7].w = float(n_stepClock >= 0.5);
  float n_stepCounter_restart = float(0.0 >= 0.5 && globalState[8].x < 0.5);
  globalState[8].x = float(0.0 >= 0.5);
  if (n_stepCounter_up > 0.5) globalState[7].z = (globalState[7].z + 1.0 - 8.0 * floor((globalState[7].z + 1.0 + 0.5) / 8.0));
  if (n_stepCounter_restart > 0.5) globalState[7].z = 0.0;
  float n_stepCounter_phase = globalState[7].z / 8.0;
  float n_stepInBar = node_modulo(globalState[7].z, n_blockCountSeq_value);
  globalState[8].y = n_stepInBar;
  float n_litWidth = mix(1.5, 0.5, clamp((globalState[2].x - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  globalState[8].z = n_litWidth;
  float n_dropFloor = globalState[3].x * iControl[0].y;
  globalState[8].w = globalState[8].w > 0.5 ? float(n_kickBand > 0.5) : float(n_kickBand >= 0.8);
  if (globalState[8].w >= 0.5 && globalState[9].z < 0.5) globalState[9].x = 1.0;
  globalState[9].z = float(globalState[8].w >= 0.5);
  float n_kickPunch_stage = globalState[9].x;
  if (n_kickPunch_stage == 1.0) globalState[9].y = min(1.0, globalState[9].y + (0.01 <= 0.0 ? 1.0 : iTimeDelta / 0.01));
  if (n_kickPunch_stage == 1.0 && globalState[9].y >= 1.0) globalState[9].x = 2.0;
  if (n_kickPunch_stage == 2.0) globalState[9].y = max(0.0, globalState[9].y - (0.45 <= 0.0 ? 1.0 : iTimeDelta / 0.45));
  if (n_kickPunch_stage == 2.0 && globalState[9].y <= 0.0) globalState[9].x = 0.0;
  if (n_kickPunch_stage == 3.0) globalState[9].y = 0.0;
  if (n_kickPunch_stage == 4.0) globalState[9].y = max(0.0, globalState[9].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_kickPunch_stage == 4.0 && globalState[9].y <= 0.0) globalState[9].x = 0.0;
  float n_floorDuck = clamp(globalState[9].y - globalState[0].z, 0.0, 1.0);
  float n_floorDrive = n_dropFloor * n_floorDuck;
  globalState[9].w = n_floorDrive;
  if (n_stepClock >= 0.5 && globalState[10].z < 0.5) globalState[10].x = 1.0;
  globalState[10].z = float(n_stepClock >= 0.5);
  float n_stepPunch_stage = globalState[10].x;
  if (n_stepPunch_stage == 1.0) globalState[10].y = min(1.0, globalState[10].y + (0.1 <= 0.0 ? 1.0 : iTimeDelta / 0.1));
  if (n_stepPunch_stage == 1.0 && globalState[10].y >= 1.0) globalState[10].x = 2.0;
  if (n_stepPunch_stage == 2.0) globalState[10].y = max(0.0, globalState[10].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_stepPunch_stage == 2.0 && globalState[10].y <= 0.0) globalState[10].x = 0.0;
  if (n_stepPunch_stage == 3.0) globalState[10].y = 0.0;
  if (n_stepPunch_stage == 4.0) globalState[10].y = max(0.0, globalState[10].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_stepPunch_stage == 4.0 && globalState[10].y <= 0.0) globalState[10].x = 0.0;
  float n_padSoft = mix(0.7, 1.0, clamp((iAudioFeatures[3].y - 0.1) / (0.3 - 0.1), 0.0, 1.0));
  float n_stepDrive = globalState[10].y * n_padSoft;
  float n_blockDrive = max(globalState[9].y, n_stepDrive);
  globalState[10].w = n_blockDrive;
  float n_hatGain = clamp(n_hatOnly * 5.0, 0.0, 1.0);
  globalState[11].x = n_hatGain;
  outGlobal = texel < 12 ? globalState[texel] : texelFetch(iGlobal, ivec2(texel, 0), 0);
}
