// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_n_in = vec3(1.0, 1.0, 1.0);
  vec3 n_n = n_n_in * min(1.0, 0.8 / max(max(n_n_in.r, max(n_n_in.g, n_n_in.b)), 0.0001));
  c = vec4(n_n, 1.0);
}
