// Generated by WLEDtoy graph mode
// checker-texture
float checker(vec3 ip) {
    vec3 p = (ip + vec3(0.000001)) * 0.999999;

    int xi = int(abs(floor(p.x)));
    int yi = int(abs(floor(p.y)));
    int zi = int(abs(floor(p.z)));

    if (((xi % 2 == yi % 2) == (zi % 2 == 1))) {
        return 1.0;
    }
    else {
        return 0.0;
    }
}

void checker_texture(
    float scale,
    vec3 Vector,
    vec3 Color1,
    vec3 Color2,
    out float Fac,
    out vec3 Color
) {
    vec3 p = Vector;

    Fac = checker(p * scale);
    Color = mix(Color2, Color1, Fac);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_fac; vec3 n_n_color; checker_texture(5.0, vec3(uv, 0.0), vec3(1.0, 1.0, 1.0), vec3(0.0, 0.0, 0.0), n_n_fac, n_n_color);
  c = vec4(vec3(n_n_fac), 1.0);
}
