// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec4 state[1];
  for (int i = 0; i < 1; i++) state[i] = vec4(0.0);
  float n_n_up = float(0.0 >= 0.5 && state[0].y < 0.5);
  state[0].y = float(0.0 >= 0.5);
  float n_n_restart = float(0.0 >= 0.5 && state[0].z < 0.5);
  state[0].z = float(0.0 >= 0.5);
  if (n_n_up > 0.5) state[0].x = (state[0].x + 1.0 - 4.0 * floor((state[0].x + 1.0 + 0.5) / 4.0));
  if (n_n_restart > 0.5) state[0].x = 0.0;
  float n_n_phase = state[0].x / 4.0;
  c = vec4(vec3(state[0].x), 1.0);
}
