// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec4 state[1];
  for (int i = 0; i < 1; i++) state[i] = vec4(0.0);
  if (0.0 >= 0.5 && state[0].z < 0.5) state[0].x = 1.0;
  if (0.0 < 0.5 && state[0].z >= 0.5 && state[0].x != 0.0) state[0].x = 4.0;
  state[0].z = float(0.0 >= 0.5);
  float n_n_stage = state[0].x;
  if (n_n_stage == 1.0) state[0].y = min(1.0, state[0].y + (0.01 <= 0.0 ? 1.0 : iTimeDelta / 0.01));
  if (n_n_stage == 1.0 && state[0].y >= 1.0) state[0].x = 2.0;
  if (n_n_stage == 2.0) state[0].y = max(0.5, state[0].y - (0.2 <= 0.0 ? 1.0 : iTimeDelta / 0.2));
  if (n_n_stage == 2.0 && state[0].y <= 0.5) state[0].x = 3.0;
  if (n_n_stage == 3.0) state[0].y = 0.5;
  if (n_n_stage == 4.0) state[0].y = max(0.0, state[0].y - (0.4 <= 0.0 ? 1.0 : iTimeDelta / 0.4));
  if (n_n_stage == 4.0 && state[0].y <= 0.0) state[0].x = 0.0;
  c = vec4(vec3(state[0].y), 1.0);
}
