// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n = abs(uv.x - 0.5) / max(max(0.5, 1.0 - 0.5), 0.0001);
  c = vec4(vec3(n_n), 1.0);
}
