// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_fac = fract(uv.x);
  vec3 n_n = vec3(1.0, 0.0, 0.0);
  n_n = mix(n_n, vec3(1.0, 1.0, 0.0), clamp((n_n_fac - 0.0) / 0.1667, 0.0, 1.0));
  n_n = mix(n_n, vec3(0.0, 1.0, 0.0), clamp((n_n_fac - 0.1667) / 0.1667, 0.0, 1.0));
  n_n = mix(n_n, vec3(0.0, 1.0, 1.0), clamp((n_n_fac - 0.3333) / 0.1667, 0.0, 1.0));
  n_n = mix(n_n, vec3(0.0, 0.0, 1.0), clamp((n_n_fac - 0.5) / 0.1667, 0.0, 1.0));
  n_n = mix(n_n, vec3(1.0, 0.0, 1.0), clamp((n_n_fac - 0.6667) / 0.1667, 0.0, 1.0));
  n_n = mix(n_n, vec3(1.0, 0.0, 0.0), clamp((n_n_fac - 0.8333) / 0.1667, 0.0, 1.0));
  c = vec4(n_n, 1.0);
}
