#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
// Generated by WLEDtoy graph mode
// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  [[maybe_unused]] float n_drift = iTime * 0.05;
  [[maybe_unused]] float n_huePosition = uv.x + n_drift;
  [[maybe_unused]] float n_palette_fac = fract(n_huePosition);
  [[maybe_unused]] vec3 n_palette = vec3(1.0, 0.0, 0.0);
  n_palette = mix(n_palette, vec3(1.0, 1.0, 0.0), clamp((n_palette_fac - 0.0) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(0.0, 1.0, 0.0), clamp((n_palette_fac - 0.1667) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(0.0, 1.0, 1.0), clamp((n_palette_fac - 0.3333) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(0.0, 0.0, 1.0), clamp((n_palette_fac - 0.5) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(1.0, 0.0, 1.0), clamp((n_palette_fac - 0.6667) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(1.0, 0.0, 0.0), clamp((n_palette_fac - 0.8333) / 0.1667, 0.0, 1.0));
  [[maybe_unused]] float n_spectrum = historyAt(0, uv.x, 0.0);
  [[maybe_unused]] float n_bandGate_edge = max(0.06, 0.0001) * 0.5;
  [[maybe_unused]] float n_bandGate = smoothstep(0.5 - n_bandGate_edge, 0.5 + n_bandGate_edge, n_spectrum);
  [[maybe_unused]] vec3 n_bands = clamp(node_mix_blend(clamp(1.0 * n_bandGate, 0.0, 1.0), vec3(0.0, 0.0, 0.0), n_palette), 0.0, 1.0);
  [[maybe_unused]] float n_kickGate_edge = max(0.1, 0.0001) * 0.5;
  [[maybe_unused]] float n_kickGate = smoothstep(0.6 - n_kickGate_edge, 0.6 + n_kickGate_edge, iAudioFeatures[2].w);
  [[maybe_unused]] float n_left = uv.x - 0.5;
  [[maybe_unused]] float n_right = 0.5 - uv.x;
  [[maybe_unused]] float n_fromCenter = max(n_left, n_right);
  [[maybe_unused]] float n_burstWidth = iAudioFeatures[2].w * 0.35;
  [[maybe_unused]] float n_burst_edge = max(0.01, 0.0001) * 0.5;
  [[maybe_unused]] float n_burst = 1.0 - smoothstep(n_burstWidth - n_burst_edge, n_burstWidth + n_burst_edge, n_fromCenter);
  [[maybe_unused]] vec3 n_flash = clamp(node_mix_blend(clamp(n_kickGate * n_burst, 0.0, 1.0), n_bands, vec3(1.0, 1.0, 1.0)), 0.0, 1.0);
  c = vec4(n_flash, 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
