// Generated by WLEDtoy graph mode
// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_drift = iTime * 0.05;
  float n_huePosition = uv.x + n_drift;
  float n_palette_fac = fract(n_huePosition);
  vec3 n_palette = vec3(1.0, 0.0, 0.0);
  n_palette = mix(n_palette, vec3(1.0, 1.0, 0.0), clamp((n_palette_fac - 0.0) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(0.0, 1.0, 0.0), clamp((n_palette_fac - 0.1667) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(0.0, 1.0, 1.0), clamp((n_palette_fac - 0.3333) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(0.0, 0.0, 1.0), clamp((n_palette_fac - 0.5) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(1.0, 0.0, 1.0), clamp((n_palette_fac - 0.6667) / 0.1667, 0.0, 1.0));
  n_palette = mix(n_palette, vec3(1.0, 0.0, 0.0), clamp((n_palette_fac - 0.8333) / 0.1667, 0.0, 1.0));
  float n_spectrum = historyAt(0, uv.x, 0.0);
  float n_bandGate_edge = max(0.06, 0.0001) * 0.5;
  float n_bandGate = smoothstep(0.5 - n_bandGate_edge, 0.5 + n_bandGate_edge, n_spectrum);
  vec3 n_bands = clamp(node_mix_blend(clamp(1.0 * n_bandGate, 0.0, 1.0), vec3(0.0, 0.0, 0.0), n_palette), 0.0, 1.0);
  float n_kickGate_edge = max(0.1, 0.0001) * 0.5;
  float n_kickGate = smoothstep(0.6 - n_kickGate_edge, 0.6 + n_kickGate_edge, bass());
  float n_left = uv.x - 0.5;
  float n_right = 0.5 - uv.x;
  float n_fromCenter = max(n_left, n_right);
  float n_burstWidth = bass() * 0.35;
  float n_burst_edge = max(0.01, 0.0001) * 0.5;
  float n_burst = 1.0 - smoothstep(n_burstWidth - n_burst_edge, n_burstWidth + n_burst_edge, n_fromCenter);
  vec3 n_flash = clamp(node_mix_blend(clamp(n_kickGate * n_burst, 0.0, 1.0), n_bands, vec3(1.0, 1.0, 1.0)), 0.0, 1.0);
  c = vec4(n_flash, 1.0);
}
