// Generated by WLEDtoy graph mode
// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_n = hsv_to_rgb(vec3(uv.x, 1.0, 1.0));
  c = vec4(n_n, 1.0);
}
