// Generated by WLEDtoy graph mode
// color-srgb-to-linear
float color_srgb_to_scene_linear(float c)
{
  if (c < 0.04045) {
    return (c < 0.0) ? 0.0 : c * (1.0 / 12.92);
  }
  else {
    return pow((c + 0.055) * (1.0 / 1.055), 2.4);
  }
}

vec3 color_srgb_to_scene_linear(vec3 c)
{
  return vec3(color_srgb_to_scene_linear(c[0]),
               color_srgb_to_scene_linear(c[1]),
               color_srgb_to_scene_linear(c[2]));
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_n_p = vec3(uv, 0.0).xy;
  vec2 n_n_st = fract(n_n_p);
  vec4 n_n_texel = texture(iImages, vec3(vec2(n_n_st.x, 1.0 - n_n_st.y), 0.0));
  vec3 n_n = n_n_texel.rgb;
  float n_n_alpha = n_n_texel.a;
  c = vec4(n_n, 1.0);
}
