// Generated by WLEDtoy graph mode
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

// noise
// Lattice cells wrap every 256 so the hash argument stays small: sin() of a large float is 0 on some GPUs,
// which painted every negative coordinate one flat value. Wrapping the corners too keeps the seams continuous.
float lattice_hash(float c) { return node_hash(mod(c, 256.0)); }
float lattice_hash(vec2 c) { return node_hash(mod(c, 256.0)); }
float lattice_hash(vec3 c) { return node_hash(dot(mod(c, 256.0), vec3(110, 241, 171))); }

float noise1(float x) {
	float i = floor(x);
	float f = fract(x);
	float u = f * f * (3.0 - 2.0 * f);
	return mix(lattice_hash(i), lattice_hash(i + 1.0), u);
}

float noise2(vec2 x) {
	vec2 i = floor(x);
	vec2 f = fract(x);

	// Four corners in 2D of a tile
	float a = lattice_hash(i);
	float b = lattice_hash(i + vec2(1.0, 0.0));
	float c = lattice_hash(i + vec2(0.0, 1.0));
	float d = lattice_hash(i + vec2(1.0, 1.0));

	vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float noise3(vec3 x) {
	vec3 i = floor(x);
	vec3 f = fract(x);

	vec3 u = f * f * (3.0 - 2.0 * f);
	return mix(mix(mix( lattice_hash(i + vec3(0, 0, 0)), lattice_hash(i + vec3(1, 0, 0)), u.x),
                   mix( lattice_hash(i + vec3(0, 1, 0)), lattice_hash(i + vec3(1, 1, 0)), u.x), u.y),
               mix(mix( lattice_hash(i + vec3(0, 0, 1)), lattice_hash(i + vec3(1, 0, 1)), u.x),
                   mix( lattice_hash(i + vec3(0, 1, 1)), lattice_hash(i + vec3(1, 1, 1)), u.x), u.y), u.z);
}

// GLSL equivalent of noise_fbm
float noise_fbm(vec3 co, float detail, float roughness, float lacunarity, bool use_normalize) {
    vec3 p = co;
    float fscale = 1.0;
    float amp = 1.0;
    float maxamp = 0.0;
    float sum = 0.0;

    // a runtime float as the bound can spin forever on a bad link; 15 octaves is past visible detail
    int octaves = int(clamp(detail, 0.0, 15.0));
    for (int i = 0; i <= octaves; i++) {
        float t = noise3(fscale * p);
        sum += t * amp;
        maxamp += amp;
        amp *= roughness;
        fscale *= lacunarity;
    }

    float rmd = detail - floor(detail);
    if (rmd != 0.0) {
        float t = noise3(fscale * p);
        float sum2 = sum + t * amp;
        return use_normalize ?
               mix(sum / maxamp, sum2 / (maxamp + amp), rmd) :
               mix(sum, sum2, rmd);
    }
    else {
        return use_normalize ? sum / maxamp : sum;
    }
}

// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

// blend-add
vec3 node_mix_add(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col1 + col2, t);
}

// blend-screen
vec3 node_mix_screen(float t, vec3 col1, vec3 col2)
{
  float tm = 1.0 - t;

  return vec3(1.0) - (vec3(tm) + t * (vec3(1.0) - col2)) * (vec3(1.0) - col1);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_polar_p = uv - vec2(0.5, 0.5);
  vec2 n_polar = vec2(atan(n_polar_p.y, n_polar_p.x) / 6.2831853 + 0.5, length(n_polar_p) * 2.0);
  // Integrator "Value" runs per frame; frozen at 0.5 when this code was taken
  float n_baseRadial = n_polar.y + 0.5;
  vec3 n_baseNoise_p = vec3(n_baseRadial) * 5.5;
  vec3 n_baseNoise_warped = n_baseNoise_p + 0.0 * (vec3(noise3(n_baseNoise_p + 13.5), noise3(n_baseNoise_p), noise3(n_baseNoise_p - 13.5)) * 2.0 - 1.0);
  float n_baseNoise_fac = noise_fbm(n_baseNoise_warped, 0.0, 0.5, 2.0, true);
  vec3 n_baseNoise_color = vec3(n_baseNoise_fac, noise_fbm(n_baseNoise_warped.yxz + 27.1, 0.0, 0.5, 2.0, true), noise_fbm(n_baseNoise_warped.zyx - 41.3, 0.0, 0.5, 2.0, true));
  float n_baseRamp_fac = n_baseNoise_fac;
  vec3 n_baseRamp = vec3(0.0, 0.0, 0.0);
  n_baseRamp = mix(n_baseRamp, vec3(0.0, 0.0, 0.0), smoothstep(0.0, 0.16, n_baseRamp_fac));
  n_baseRamp = mix(n_baseRamp, vec3(0.0, 0.03, 0.55), smoothstep(0.16, 0.32, n_baseRamp_fac));
  n_baseRamp = mix(n_baseRamp, vec3(0.35, 0.0, 0.9), smoothstep(0.32, 0.52, n_baseRamp_fac));
  n_baseRamp = mix(n_baseRamp, vec3(0.95, 0.05, 0.5), smoothstep(0.52, 0.84, n_baseRamp_fac));
  // Envelope Follower "Envelope" runs per frame; frozen at 0.5 when this code was taken
  float n_breathWave_cycle = iTime * 0.25 + 0.5;
  float n_breathWave_p = fract(n_breathWave_cycle);
  float n_breathWave = 0.5 - 0.5 * cos(6.2831853 * n_breathWave_p);
  float n_baseLevel = mix(0.2, n_breathWave, clamp((0.5 - 0.1) / (0.3 - 0.1), 0.0, 1.0));
  // Envelope Follower "Envelope" runs per frame; frozen at 0.5 when this code was taken
  float n_quietBoost = mix(1.0, 0.2, clamp(0.5, 0.0, 1.0));
  vec3 n_baseLayer = clamp(node_mix_blend(clamp(n_baseLevel * n_quietBoost, 0.0, 1.0), vec3(0.0, 0.0, 0.0), n_baseRamp), 0.0, 1.0);
  // Sample and Hold "Value" runs per frame; frozen at 0.5 when this code was taken
  vec3 n_ringColorA = hsv_to_rgb(vec3(0.5, 1.0, 1.0));
  // Envelope Follower "Envelope" runs per frame; frozen at 0.5 when this code was taken
  float n_ringPower = mix(0.6, 1.0, clamp((0.5 - 0.38) / (0.52 - 0.38), 0.0, 1.0));
  float n_ringFalloff = mix(n_ringPower, 0.0, clamp((n_polar.y - 0.0) / (1.8 - 0.0), 0.0, 1.0));
  // Integrator "Value" runs per frame; frozen at 0.5 when this code was taken
  float n_ringDistA = 0.5 - n_polar.y;
  // Envelope "Envelope" runs per frame; frozen at 0.5 when this code was taken
  float n_ringLead = mix(0.0, -0.18, clamp((0.5 - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  float n_ringThickness = mix(0.09, 0.22, clamp((0.5 - 0.38) / (0.52 - 0.38), 0.0, 1.0));
  float n_ringMaskA_edge = max(0.05, 0.0001) * 0.5;
  float n_ringMaskA_lo = min(n_ringLead, n_ringThickness);
  float n_ringMaskA_hi = max(n_ringLead, n_ringThickness);
  float n_ringMaskA = smoothstep(n_ringMaskA_lo - n_ringMaskA_edge, n_ringMaskA_lo + n_ringMaskA_edge, n_ringDistA) * (1.0 - smoothstep(n_ringMaskA_hi - n_ringMaskA_edge, n_ringMaskA_hi + n_ringMaskA_edge, n_ringDistA));
  vec3 n_addRingA = clamp(node_mix_add(clamp(n_ringFalloff * n_ringMaskA, 0.0, 1.0), n_baseLayer, n_ringColorA), 0.0, 1.0);
  // Sample and Hold "Value" runs per frame; frozen at 0.5 when this code was taken
  vec3 n_ringColorB = hsv_to_rgb(vec3(0.5, 1.0, 1.0));
  // Integrator "Value" runs per frame; frozen at 0.5 when this code was taken
  float n_ringDistB = 0.5 - n_polar.y;
  float n_ringMaskB_edge = max(0.05, 0.0001) * 0.5;
  float n_ringMaskB_lo = min(n_ringLead, n_ringThickness);
  float n_ringMaskB_hi = max(n_ringLead, n_ringThickness);
  float n_ringMaskB = smoothstep(n_ringMaskB_lo - n_ringMaskB_edge, n_ringMaskB_lo + n_ringMaskB_edge, n_ringDistB) * (1.0 - smoothstep(n_ringMaskB_hi - n_ringMaskB_edge, n_ringMaskB_hi + n_ringMaskB_edge, n_ringDistB));
  vec3 n_addRingB = clamp(node_mix_add(clamp(n_ringFalloff * n_ringMaskB, 0.0, 1.0), n_addRingA, n_ringColorB), 0.0, 1.0);
  // Integrator "Value" runs per frame; frozen at 0.5 when this code was taken
  float n_spokes_cycle = n_polar.x * 6.0 + 0.5;
  float n_spokes_p = fract(n_spokes_cycle);
  float n_spokes = 0.5 - 0.5 * cos(6.2831853 * n_spokes_p);
  float n_snareRamp_fac = n_spokes;
  vec3 n_snareRamp = vec3(0.0, 0.25, 1.0);
  n_snareRamp = mix(n_snareRamp, vec3(0.05, 0.85, 1.0), smoothstep(0.0, 0.55, n_snareRamp_fac));
  n_snareRamp = mix(n_snareRamp, vec3(0.6, 0.95, 1.0), smoothstep(0.55, 1.0, n_snareRamp_fac));
  // Envelope "Envelope" runs per frame; frozen at 0.5 when this code was taken
  float n_snareReach = mix(1.55, 0.85, clamp((0.5 - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  float n_snareRim_edge = max(0.12, 0.0001) * 0.5;
  float n_snareRim = smoothstep(n_snareReach - n_snareRim_edge, n_snareReach + n_snareRim_edge, n_polar.y);
  vec3 n_addSnare = clamp(node_mix_screen(clamp(0.9 * n_snareRim, 0.0, 1.0), n_addRingB, n_snareRamp), 0.0, 1.0);
  // Knob "Value" runs per frame; frozen at 0.5 when this code was taken
  vec3 n_wake = max(n_addSnare, previousFrame(0.0) * exp(-iTimeDelta / max(0.5, 0.0001)));
  c = vec4(n_wake, 1.0);
}
