#include "wledtoy.h"

namespace wledtoy {

constexpr int ledCount = 30;
// Generated by WLEDtoy graph mode
// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

void mainImage(vec4& c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  [[maybe_unused]] vec3 n_n = clamp(node_mix_blend(clamp(1.0 * 1.0, 0.0, 1.0), vec3(0.0, 0.0, 0.0), vec3(1.0, 1.0, 1.0)), 0.0, 1.0);
  c = vec4(n_n, 1.0);
}


void renderFrame(float time, int frameIndex, vec3* colors) {
  iTime = time;
  iFrame = frameIndex;
  iLedCount = float(ledCount);
  iResolution = vec3(float(ledCount), 1.0f, 1.0f);
  for (int i = 0; i < ledCount; i++) {
    float ledIndex = float(i);
    vec2 uv = iLayoutCount > 0.5f ? vec2(ledLayout(ledIndex).xy) : vec2((ledIndex + 0.5f) / iLedCount, iScanY);
    vec4 c(0.0f, 0.0f, 0.0f, 1.0f);
    mainImage(c, uv, ledIndex);
    colors[i] = clamp(vec3(c.xyz), 0.0f, 1.0f);
  }
}

}
