// Generated by WLEDtoy graph mode
// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_n = clamp(node_mix_blend(clamp(1.0 * 1.0, 0.0, 1.0), vec3(0.0, 0.0, 0.0), vec3(1.0, 1.0, 1.0)), 0.0, 1.0);
  c = vec4(n_n, 1.0);
}
