// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_n_folded = 1.0 - abs(uv - vec2(0.5, 0.5)) / max(vec2(0.5, 0.5), 1.0 - vec2(0.5, 0.5));
  vec2 n_n = vec2(n_n_folded.x, uv.y);
  c = vec4(vec3(n_n, 0.0), 1.0);
}
