// Generated by WLEDtoy graph mode
uniform highp sampler2D iGlobal;
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

// color-rgb-to-hsv
vec3 rgb_to_hsv(vec3 rgb)
{
  float cmax, cmin, h, s, v, cdelta;
  vec3 c;

  cmax = max(rgb[0], max(rgb[1], rgb[2]));
  cmin = min(rgb[0], min(rgb[1], rgb[2]));
  cdelta = cmax - cmin;

  v = cmax;

  if (cmax != 0.0) {
    s = cdelta / cmax;
  }
  else {
    s = 0.0;
    h = 0.0;
  }

  if (s == 0.0) {
    h = 0.0;
  }
  else {
    c = (vec3(cmax, cmax, cmax) - rgb) / cdelta;

    if (rgb[0] == cmax) {
      h = c[2] - c[1];
    }
    else if (rgb[1] == cmax) {
      h = 2.0 + c[0] - c[2];
    }
    else {
      h = 4.0 + c[1] - c[0];
    }

    h /= 6.0;

    if (h < 0.0) {
      h += 1.0;
    }
  }

  return vec3(h, s, v);
}

// color-hsv-to-rgb
vec3 hsv_to_rgb(vec3 hsv)
{
  float i, f, p, q, t, h, s, v;
  vec3 rgb;

  // Blender only folds h == 1.0 back to 0; hue is a circle, so anything outside 0..1 wraps
  h = fract(hsv[0]);
  s = hsv[1];
  v = hsv[2];

  if (s == 0.0) {
    rgb = vec3(v, v, v);
  }
  else {
    h *= 6.0;
    i = floor(h);
    f = h - i;
    rgb = vec3(f, f, f);
    p = v * (1.0 - s);
    q = v * (1.0 - (s * f));
    t = v * (1.0 - (s * (1.0 - f)));

    if (i == 0.0) {
      rgb = vec3(v, t, p);
    }
    else if (i == 1.0) {
      rgb = vec3(q, v, p);
    }
    else if (i == 2.0) {
      rgb = vec3(p, v, t);
    }
    else if (i == 3.0) {
      rgb = vec3(p, q, v);
    }
    else if (i == 4.0) {
      rgb = vec3(t, p, v);
    }
    else {
      rgb = vec3(v, p, q);
    }
  }

  return rgb;
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec4 n_ledLayout = ledLayout(ledIndex);
  vec3 n_sparkCoords = vec3(ledIndex, texelFetch(iGlobal, ivec2(2, 0), 0).z, 0.0);
  float n_sparkNoise_fac = node_hash(n_sparkCoords.xy + n_sparkCoords.z);
  vec3 n_sparkNoise = vec3(n_sparkNoise_fac, node_hash(n_sparkCoords.yz + 17.3 + n_sparkCoords.x), node_hash(n_sparkCoords.zx + 41.7 + n_sparkCoords.y));
  float n_sparkPick_edge = max(0.01, 0.0001) * 0.5;
  float n_sparkPick = smoothstep(0.93 - n_sparkPick_edge, 0.93 + n_sparkPick_edge, n_sparkNoise_fac);
  vec3 n_sparkLayer = clamp(node_mix_blend(clamp(texelFetch(iGlobal, ivec2(1, 0), 0).w * n_sparkPick, 0.0, 1.0), vec3(0.0, 0.0, 0.0), vec3(0.6, 0.9, 1.0)), 0.0, 1.0);
  vec2 n_mirror_folded = abs(uv - vec2(0.5, 0.5)) / max(vec2(0.5, 0.5), 1.0 - vec2(0.5, 0.5));
  vec2 n_mirror = n_mirror_folded;
  float n_radius = length(vec3(n_mirror, 0.0));
  float n_meteorMask_edge = max(0.02, 0.0001) * 0.5;
  float n_meteorMask_lo = min(texelFetch(iGlobal, ivec2(5, 0), 0).z, texelFetch(iGlobal, ivec2(5, 0), 0).y);
  float n_meteorMask_hi = max(texelFetch(iGlobal, ivec2(5, 0), 0).z, texelFetch(iGlobal, ivec2(5, 0), 0).y);
  float n_meteorMask = smoothstep(n_meteorMask_lo - n_meteorMask_edge, n_meteorMask_lo + n_meteorMask_edge, n_radius) * (1.0 - smoothstep(n_meteorMask_hi - n_meteorMask_edge, n_meteorMask_hi + n_meteorMask_edge, n_radius));
  vec3 n_meteorLayer = clamp(node_mix_blend(clamp(texelFetch(iGlobal, ivec2(4, 0), 0).y * n_meteorMask, 0.0, 1.0), n_sparkLayer, vec3(0.9, 0.25, 1.0)), 0.0, 1.0);
  float n_heat = texelFetch(iGlobal, ivec2(6, 0), 0).x * 0.5 + n_radius;
  float n_barRamp_fac = n_heat;
  vec3 n_barRamp = vec3(0.0, 0.35, 0.8);
  n_barRamp = mix(n_barRamp, vec3(0.0, 0.65, 0.6), clamp((n_barRamp_fac - 0.0) / 0.2, 0.0, 1.0));
  n_barRamp = mix(n_barRamp, vec3(0.0, 0.8, 0.25), clamp((n_barRamp_fac - 0.2) / 0.22, 0.0, 1.0));
  n_barRamp = mix(n_barRamp, vec3(0.95, 0.65, 0.0), clamp((n_barRamp_fac - 0.42) / 0.18, 0.0, 1.0));
  n_barRamp = mix(n_barRamp, vec3(1.0, 0.16, 0.0), clamp((n_barRamp_fac - 0.6) / 0.2, 0.0, 1.0));
  n_barRamp = mix(n_barRamp, vec3(1.0, 0.0, 0.3), clamp((n_barRamp_fac - 0.8) / 0.2, 0.0, 1.0));
  vec3 n_barShade = n_barRamp * vec3(texelFetch(iGlobal, ivec2(6, 0), 0).z);
  float n_segments_n = max(1.0, floor(6.0));
  float n_segments_scaled = clamp(n_radius, 0.0, 0.999999) * n_segments_n;
  float n_segments_segment = floor(n_segments_scaled);
  float n_segments = fract(n_segments_scaled);
  float n_segments_fraction = n_segments_segment / max(1.0, n_segments_n - 1.0);
  float n_segmentGaps_edge = max(0.04, 0.0001) * 0.5;
  float n_segmentGaps_lo = min(0.0, 0.8);
  float n_segmentGaps_hi = max(0.0, 0.8);
  float n_segmentGaps = smoothstep(n_segmentGaps_lo - n_segmentGaps_edge, n_segmentGaps_lo + n_segmentGaps_edge, n_segments) * (1.0 - smoothstep(n_segmentGaps_hi - n_segmentGaps_edge, n_segmentGaps_hi + n_segmentGaps_edge, n_segments));
  float n_barMask_edge = max(0.03, 0.0001) * 0.5;
  float n_barMask = 1.0 - smoothstep(texelFetch(iGlobal, ivec2(6, 0), 0).w - n_barMask_edge, texelFetch(iGlobal, ivec2(6, 0), 0).w + n_barMask_edge, n_radius);
  vec3 n_barLayer = clamp(node_mix_blend(clamp(n_segmentGaps * n_barMask, 0.0, 1.0), n_meteorLayer, n_barShade), 0.0, 1.0);
  float n_peakDot_edge = max(0.015, 0.0001) * 0.5;
  float n_peakDot_lo = min(texelFetch(iGlobal, ivec2(8, 0), 0).y, texelFetch(iGlobal, ivec2(8, 0), 0).z);
  float n_peakDot_hi = max(texelFetch(iGlobal, ivec2(8, 0), 0).y, texelFetch(iGlobal, ivec2(8, 0), 0).z);
  float n_peakDot = smoothstep(n_peakDot_lo - n_peakDot_edge, n_peakDot_lo + n_peakDot_edge, n_radius) * (1.0 - smoothstep(n_peakDot_hi - n_peakDot_edge, n_peakDot_hi + n_peakDot_edge, n_radius));
  vec3 n_peakLayer = clamp(node_mix_blend(clamp(1.0 * n_peakDot, 0.0, 1.0), n_barLayer, vec3(1.0, 0.9, 0.75)), 0.0, 1.0);
  vec3 n_hueRotate_hsv = rgb_to_hsv(n_peakLayer);
  vec3 n_hueRotate = mix(n_peakLayer, max(hsv_to_rgb(vec3(fract(n_hueRotate_hsv.x + iControl[0].x), clamp(n_hueRotate_hsv.y * 1.0, 0.0, 1.0), n_hueRotate_hsv.z * 1.0)), vec3(0.0)), 1.0);
  vec3 n_trails = max(n_hueRotate, previousFrame(0.0) * exp(-iTimeDelta / max(iControl[0].z, 0.0001)));
  c = vec4(n_trails, 1.0);
}
