// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n = fract(sin(ledIndex * 127.1 + 311.7) * 43758.5453);
  c = vec4(vec3(n_n), 1.0);
}
