// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_edge = max(0.0, 0.0001) * 0.5;
  float n_n_lo = min(0.25, 0.75);
  float n_n_hi = max(0.25, 0.75);
  float n_n = smoothstep(n_n_lo - n_n_edge, n_n_lo + n_n_edge, uv.x) * (1.0 - smoothstep(n_n_hi - n_n_edge, n_n_hi + n_n_edge, uv.x));
  c = vec4(vec3(n_n), 1.0);
}
