// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n = mix(0.0, 1.0, clamp((uv.x - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  c = vec4(vec3(n_n), 1.0);
}
