// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_a = 0.0 * 6.2831853;
  vec2 n_n_p = uv - vec2(0.5, 0.5);
  vec2 n_n = vec2(n_n_p.x * cos(n_n_a) + n_n_p.y * sin(n_n_a), n_n_p.y * cos(n_n_a) - n_n_p.x * sin(n_n_a)) + vec2(0.5, 0.5);
  c = vec4(vec3(n_n, 0.0), 1.0);
}
