// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec4 state[1];
  for (int i = 0; i < 1; i++) state[i] = vec4(0.0);
  state[0].x = state[0].x > 0.5 ? float(0.0 > 0.4) : float(0.0 >= 0.6);
  c = vec4(vec3(state[0].x), 1.0);
}
