// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_n = max(1.0, floor(4.0));
  float n_n_scaled = clamp(uv.x, 0.0, 0.999999) * n_n_n;
  float n_n_segment = floor(n_n_scaled);
  float n_n = fract(n_n_scaled);
  float n_n_fraction = n_n_segment / max(1.0, n_n_n - 1.0);
  c = vec4(vec3(n_n), 1.0);
}
