// Generated by WLEDtoy graph mode
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

// noise
// Lattice cells wrap every 256 so the hash argument stays small: sin() of a large float is 0 on some GPUs,
// which painted every negative coordinate one flat value. Wrapping the corners too keeps the seams continuous.
float lattice_hash(float c) { return node_hash(mod(c, 256.0)); }
float lattice_hash(vec2 c) { return node_hash(mod(c, 256.0)); }
float lattice_hash(vec3 c) { return node_hash(dot(mod(c, 256.0), vec3(110, 241, 171))); }

float noise1(float x) {
	float i = floor(x);
	float f = fract(x);
	float u = f * f * (3.0 - 2.0 * f);
	return mix(lattice_hash(i), lattice_hash(i + 1.0), u);
}

float noise2(vec2 x) {
	vec2 i = floor(x);
	vec2 f = fract(x);

	// Four corners in 2D of a tile
	float a = lattice_hash(i);
	float b = lattice_hash(i + vec2(1.0, 0.0));
	float c = lattice_hash(i + vec2(0.0, 1.0));
	float d = lattice_hash(i + vec2(1.0, 1.0));

	vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float noise3(vec3 x) {
	vec3 i = floor(x);
	vec3 f = fract(x);

	vec3 u = f * f * (3.0 - 2.0 * f);
	return mix(mix(mix( lattice_hash(i + vec3(0, 0, 0)), lattice_hash(i + vec3(1, 0, 0)), u.x),
                   mix( lattice_hash(i + vec3(0, 1, 0)), lattice_hash(i + vec3(1, 1, 0)), u.x), u.y),
               mix(mix( lattice_hash(i + vec3(0, 0, 1)), lattice_hash(i + vec3(1, 0, 1)), u.x),
                   mix( lattice_hash(i + vec3(0, 1, 1)), lattice_hash(i + vec3(1, 1, 1)), u.x), u.y), u.z);
}

// GLSL equivalent of noise_fbm
float noise_fbm(vec3 co, float detail, float roughness, float lacunarity, bool use_normalize) {
    vec3 p = co;
    float fscale = 1.0;
    float amp = 1.0;
    float maxamp = 0.0;
    float sum = 0.0;

    // a runtime float as the bound can spin forever on a bad link; 15 octaves is past visible detail
    int octaves = int(clamp(detail, 0.0, 15.0));
    for (int i = 0; i <= octaves; i++) {
        float t = noise3(fscale * p);
        sum += t * amp;
        maxamp += amp;
        amp *= roughness;
        fscale *= lacunarity;
    }

    float rmd = detail - floor(detail);
    if (rmd != 0.0) {
        float t = noise3(fscale * p);
        float sum2 = sum + t * amp;
        return use_normalize ?
               mix(sum / maxamp, sum2 / (maxamp + amp), rmd) :
               mix(sum, sum2, rmd);
    }
    else {
        return use_normalize ? sum / maxamp : sum;
    }
}

// blend-mix
vec3 node_mix_blend(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col2, t);
}

// blend-screen
vec3 node_mix_screen(float t, vec3 col1, vec3 col2)
{
  float tm = 1.0 - t;

  return vec3(1.0) - (vec3(tm) + t * (vec3(1.0) - col2)) * (vec3(1.0) - col1);
}

// blend-add
vec3 node_mix_add(float t, vec3 col1, vec3 col2)
{
  return mix(col1, col1 + col2, t);
}

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_curtainCoords_p = (vec3(uv, 0.0) - vec3(0.0, 0.0, 0.0)) * vec3(4.0, 0.35, 1.0);
  float n_curtainCoords_a = 0.03 * 6.2831853;
  vec3 n_curtainCoords = vec3(n_curtainCoords_p.x * cos(n_curtainCoords_a) + n_curtainCoords_p.y * sin(n_curtainCoords_a), n_curtainCoords_p.y * cos(n_curtainCoords_a) - n_curtainCoords_p.x * sin(n_curtainCoords_a), n_curtainCoords_p.z) + vec3(0.0, 0.0, 0.0) + vec3(iControl[0].x, iControl[0].y, iControl[0].z);
  vec3 n_curtainNoise_p = n_curtainCoords * 2.0;
  vec3 n_curtainNoise_warped = n_curtainNoise_p + 0.5 * (vec3(noise3(n_curtainNoise_p + 13.5), noise3(n_curtainNoise_p), noise3(n_curtainNoise_p - 13.5)) * 2.0 - 1.0);
  float n_curtainNoise_fac = noise_fbm(n_curtainNoise_warped, 2.5, 0.55, 2.0, true);
  vec3 n_curtainNoise_color = vec3(n_curtainNoise_fac, noise_fbm(n_curtainNoise_warped.yxz + 27.1, 2.5, 0.55, 2.0, true), noise_fbm(n_curtainNoise_warped.zyx - 41.3, 2.5, 0.55, 2.0, true));
  float n_curtainShape = smoothstep(0.33, 0.66, n_curtainNoise_fac);
  float n_curtainHue = n_curtainShape * 0.75 + iControl[0].w;
  float n_curtainRamp_fac = n_curtainHue;
  vec3 n_curtainRamp = vec3(0.16, 0.0, 0.5);
  n_curtainRamp = mix(n_curtainRamp, vec3(0.35, 0.0, 0.95), smoothstep(0.0, 0.35, n_curtainRamp_fac));
  n_curtainRamp = mix(n_curtainRamp, vec3(0.0, 0.4, 0.6), smoothstep(0.35, 0.6, n_curtainRamp_fac));
  n_curtainRamp = mix(n_curtainRamp, vec3(0.0, 0.8, 0.4), smoothstep(0.6, 0.85, n_curtainRamp_fac));
  n_curtainRamp = mix(n_curtainRamp, vec3(0.1, 1.0, 0.3), smoothstep(0.85, 1.0, n_curtainRamp_fac));
  vec3 n_curtainLayer = clamp(node_mix_blend(clamp(iControl[1].x * n_curtainShape, 0.0, 1.0), vec3(0.0, 0.0, 0.0), n_curtainRamp), 0.0, 1.0);
  float n_rowOffset = uv.y - iScanY;
  float n_horizonDistance = abs(n_rowOffset);
  float n_age = clamp(n_horizonDistance * iControl[1].z, 0.0, 1.0);
  float n_waterfall = historyAt(1, uv.x, n_age);
  float n_trebleTilt = mix(1.0, iControl[1].w, clamp((uv.x - 0.0) / (1.0 - 0.0), 0.0, 1.0));
  float n_tiltedLevel = n_waterfall * n_trebleTilt;
  float n_levelShaped = smoothstep(0.13, iControl[1].y, n_tiltedLevel);
  float n_historyHeat = mix(0.7, 0.85, clamp((n_horizonDistance - 0.0) / (0.06 - 0.0), 0.0, 1.0));
  float n_colorOffset = n_curtainShape * 0.2 + iControl[2].x;
  float n_rampPosition = n_levelShaped * n_historyHeat + n_colorOffset;
  float n_auroraRamp_fac = n_rampPosition;
  vec3 n_auroraRamp = vec3(0.14, 0.0, 0.5);
  n_auroraRamp = mix(n_auroraRamp, vec3(0.35, 0.0, 1.0), clamp((n_auroraRamp_fac - 0.0) / 0.22, 0.0, 1.0));
  n_auroraRamp = mix(n_auroraRamp, vec3(0.0, 0.55, 0.65), clamp((n_auroraRamp_fac - 0.22) / 0.23, 0.0, 1.0));
  n_auroraRamp = mix(n_auroraRamp, vec3(0.02, 1.0, 0.22), clamp((n_auroraRamp_fac - 0.45) / 0.23, 0.0, 1.0));
  n_auroraRamp = mix(n_auroraRamp, vec3(0.02, 1.0, 0.22), clamp((n_auroraRamp_fac - 0.68) / 0.16, 0.0, 1.0));
  n_auroraRamp = mix(n_auroraRamp, vec3(1.0, 0.75, 0.04), clamp((n_auroraRamp_fac - 0.84) / 0.06, 0.0, 1.0));
  n_auroraRamp = mix(n_auroraRamp, vec3(1.0, 0.05, 0.4), clamp((n_auroraRamp_fac - 0.9) / 0.06, 0.0, 1.0));
  n_auroraRamp = mix(n_auroraRamp, vec3(1.0, 0.05, 0.4), clamp((n_auroraRamp_fac - 0.96) / 0.04, 0.0, 1.0));
  float n_heightFade = mix(1.0, 0.75, clamp((n_horizonDistance - 0.0) / (0.5 - 0.0), 0.0, 1.0));
  float n_fadedLevel = n_levelShaped * n_heightFade;
  float n_curtainGate = mix(0.5, 1.0, clamp(n_curtainShape, 0.0, 1.0));
  float n_waterfallBrightness = clamp(n_fadedLevel * n_curtainGate, 0.0, 1.0);
  vec3 n_waterfallOverCurtain = clamp(node_mix_screen(clamp(1.0 * n_waterfallBrightness, 0.0, 1.0), n_curtainLayer, n_auroraRamp), 0.0, 1.0);
  float n_hatSparkle = sparkle(ledIndex, iControl[2].y, 7.0);
  float n_trebleRegion = smoothstep(0.62, 0.85, uv.x);
  float n_trebleHits = clamp(n_trebleRegion * n_fadedLevel, 0.0, 1.0);
  vec3 n_sparkleLayer = clamp(node_mix_add(clamp(n_hatSparkle * n_trebleHits, 0.0, 1.0), n_waterfallOverCurtain, vec3(1.0, 0.15, 0.55)), 0.0, 1.0);
  float n_trailDecay = n_horizonDistance * -0.5 + iControl[2].z;
  vec3 n_glowTrails = max(n_sparkleLayer, previousFrame(0.0) * exp(-iTimeDelta / max(n_trailDecay, 0.0001)));
  c = vec4(n_glowTrails, 1.0);
}
