// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  // Step Sequencer "Value" runs per frame; frozen at 0.5 when this code was taken
  c = vec4(vec3(0.5), 1.0);
}
