// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_n_scaled = uv * vec2(4.0, 1.0);
  vec2 n_n = fract(n_n_scaled);
  vec2 n_n_cell = floor(n_n_scaled);
  c = vec4(vec3(n_n, 0.0), 1.0);
}
