// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec3 n_n = max(vec3(0.0, 0.0, 0.0), previousFrame(0.0) * exp(-iTimeDelta / max(0.5, 0.0001)));
  c = vec4(n_n, 1.0);
}
