// Generated by WLEDtoy graph mode
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  vec2 n_n_p = vec3(uv, 0.0).xy * 5.0;
  vec2 n_n_cell = floor(n_n_p);
  float n_n_best = 8.0; vec2 n_n_nearest = n_n_cell;
  for (int j = -1; j <= 1; j++) for (int i = -1; i <= 1; i++) {
    vec2 g = n_n_cell + vec2(float(i), float(j));
    vec2 o = g + 0.5 + (vec2(node_hash(g), node_hash(g + 19.1)) - 0.5) * 1.0;
    float d = distance(o, n_n_p);
    if (d < n_n_best) { n_n_best = d; n_n_nearest = o; }
  }
  float n_n_distance = n_n_best;
  vec3 n_n_color = vec3(node_hash(n_n_nearest), node_hash(n_n_nearest + 7.7), node_hash(n_n_nearest + 13.9));
  vec3 n_n_position = vec3(n_n_nearest / 5.0, 0.0);
  c = vec4(vec3(n_n_distance), 1.0);
}
