// Generated by WLEDtoy graph mode
void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_cycle = iTime * 1.0 + 0.0;
  float n_n_p = fract(n_n_cycle);
  float n_n = 0.5 - 0.5 * cos(6.2831853 * n_n_p);
  c = vec4(vec3(n_n), 1.0);
}
