// Generated by WLEDtoy graph mode
// common
#define M_PI 3.1415926535897932384626433832795
#define M_2PI 6.283185307179586476925286766559

// https://www.shadertoy.com/view/3sd3Rs
float node_hash(float n) { return fract(sin(n) * 1e4); }
float node_hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

void mainImage(out vec4 c, vec2 uv, float ledIndex) {
  c = vec4(0.0, 0.0, 0.0, 1.0);
  float n_n_fac = node_hash(vec3(uv, 0.0).xy + vec3(uv, 0.0).z);
  vec3 n_n = vec3(n_n_fac, node_hash(vec3(uv, 0.0).yz + 17.3 + vec3(uv, 0.0).x), node_hash(vec3(uv, 0.0).zx + 41.7 + vec3(uv, 0.0).y));
  c = vec4(vec3(n_n_fac), 1.0);
}
